import type { DefaultDialogueBundleDef, DefaultDialogueTurn } from './defaultDialogueLibrary'
import type { RelationshipType } from './relationshipConfig'

/**
 * Relationship-specific default conversations (static data merged into
 * `DEFAULT_DIALOGUE_BUNDLES`; never copied into a user's saved data).
 *
 *   neutral-XX  30  no `relationshipTypes` — usable by every pair, and the ONLY
 *                   default content a pair whose relationship was never chosen gets
 *   friend-XX   30  `['friend']`
 *   close-XX    30  `['close']`   (친밀한 관계 — the "절친" flavor)
 *
 * Families, rivals, awkward pairs and the extra 연인/부부 bundles follow in later
 * batches. Filtering is by relationship id (`relationshipTypes`) plus whether the
 * pair's relationship was actually chosen — never by wording.
 *
 * Authoring rules: each bundle is one connected 2-4 turn exchange; both the
 * 존댓말 and 반말 text of every turn is hand-written (never a suffix added to the
 * other); no forms of address, nicknames, kinship or rank terms; no invented
 * past events, ages, jobs or family; no claim that something unimplemented
 * (cooking, sleeping, work, buying) happened — only the moment, the time of day,
 * the room and feelings, with meals/rest only ever asked about or proposed;
 * nothing romantic. Personality reads through each turn's `emotion`/`tags`
 * (`lineAffinity`) and text length.
 */

const F = 'first' as const
const S = 'second' as const

const NEU: string[] = []
const WARM = ['다정']
const PLAY = ['장난']
const CALM = ['차분']
const GLAD = ['반가']
const SHY = ['수줍']

function t(speaker: 'first' | 'second', emotion: string, tags: string[], formal: string, casual: string): DefaultDialogueTurn {
  return { speaker, emotion, tags, text: { formal, casual } }
}

function b(id: string, categoryId: string, relationshipTypes: RelationshipType[] | undefined, ...turns: DefaultDialogueTurn[]): DefaultDialogueBundleDef {
  return relationshipTypes ? { id, categoryId, relationshipTypes, turns } : { id, categoryId, turns }
}

const FRIEND: RelationshipType[] = ['friend']
const CLOSE: RelationshipType[] = ['close']

/** 공용·중립 (30) — safe for any pair, including one whose relationship was never chosen. */
export const NEUTRAL_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('neutral-01', 'morning-greeting', undefined,
    t(F, 'calm', CALM, '좋은 아침이에요. 오늘은 공기가 상쾌하네요.', '좋은 아침. 오늘은 공기가 상쾌하네.'),
    t(S, 'calm', CALM, '그러게요. 하루를 시작하기 좋은 아침이에요.', '그러게. 하루를 시작하기 좋은 아침이야.')),
  b('neutral-02', 'morning-greeting', undefined,
    t(F, 'neutral', NEU, '아침 햇살이 참 좋네요.', '아침 햇살이 참 좋네.'),
    t(S, 'neutral', NEU, '네, 방 안이 환해서 기분이 좋아지네요.', '응, 방 안이 환해서 기분이 좋아지네.'),
    t(F, 'calm', CALM, '오늘도 무리하지 말고 천천히 지내요.', '오늘도 무리하지 말고 천천히 지내자.')),
  b('neutral-03', 'wake-up', undefined,
    t(F, 'neutral', NEU, '아직 졸린 얼굴이시네요.', '아직 졸린 얼굴이네.'),
    t(S, 'calm', CALM, '조금요. 곧 괜찮아질 거예요.', '조금. 곧 괜찮아질 거야.')),
  b('neutral-04', 'breakfast', undefined,
    t(F, 'neutral', NEU, '아침 식사는 어떻게 하실 거예요?', '아침은 어떻게 할 거야?'),
    t(S, 'neutral', NEU, '아직 정하지 못했어요. 가볍게 생각하고 있어요.', '아직 못 정했어. 가볍게 생각 중이야.')),
  b('neutral-05', 'lunch', undefined,
    t(F, 'neutral', NEU, '점심시간이 다 됐네요.', '점심시간이 다 됐네.'),
    t(S, 'neutral', NEU, '그러게요. 시간이 꽤 빠르게 가요.', '그러게. 시간이 꽤 빠르게 가.')),
  b('neutral-06', 'lunch', undefined,
    t(F, 'curious', NEU, '점심은 가볍게 드시는 편이세요?', '점심은 가볍게 먹는 편이야?'),
    t(S, 'neutral', NEU, '그때그때 달라요. 그날 기분에 따라 정해요.', '그때그때 달라. 그날 기분에 따라 정해.')),
  b('neutral-07', 'afternoon-chat', undefined,
    t(F, 'calm', CALM, '오후가 되니 조금 나른하네요.', '오후가 되니 조금 나른하네.'),
    t(S, 'calm', CALM, '맞아요. 이럴 땐 잠깐 쉬어 가는 것도 좋아요.', '맞아. 이럴 땐 잠깐 쉬어 가는 것도 좋아.')),
  b('neutral-08', 'afternoon-chat', undefined,
    t(F, 'neutral', NEU, '요즘 날씨가 지내기 편하네요.', '요즘 날씨가 지내기 편하네.'),
    t(S, 'neutral', NEU, '네, 너무 덥지도 춥지도 않아서 좋아요.', '응, 너무 덥지도 춥지도 않아서 좋아.')),
  b('neutral-09', 'snack', undefined,
    t(F, 'neutral', NEU, '출출한 시간이네요.', '출출한 시간이네.'),
    t(S, 'neutral', NEU, '그러게요. 간단한 간식이 생각나요.', '그러게. 간단한 간식이 생각나.')),
  b('neutral-10', 'snack', undefined,
    t(F, 'calm', CALM, '간식 시간이라 그런지 마음이 느긋해져요.', '간식 시간이라 그런지 마음이 느긋해져.'),
    t(S, 'calm', CALM, '저도요. 잠깐 쉬어 가는 시간 같아요.', '나도. 잠깐 쉬어 가는 시간 같아.')),
  b('neutral-11', 'dinner', undefined,
    t(F, 'neutral', NEU, '저녁 시간이 다가오네요.', '저녁 시간이 다가오네.'),
    t(S, 'neutral', NEU, '네, 하루가 금방 지나가는 것 같아요.', '응, 하루가 금방 지나가는 것 같아.')),
  b('neutral-12', 'dinner', undefined,
    t(F, 'calm', CALM, '저녁은 편하게 정하고 싶어요.', '저녁은 편하게 정하고 싶어.'),
    t(S, 'calm', CALM, '그것도 좋은 생각이에요. 무리하지 않는 게 제일이죠.', '그것도 좋은 생각이야. 무리하지 않는 게 제일이지.')),
  b('neutral-13', 'day-wrap-up', undefined,
    t(F, 'calm', CALM, '오늘 하루가 벌써 저물어 가네요.', '오늘 하루가 벌써 저물어 가네.'),
    t(S, 'calm', CALM, '네, 이 시간이 되면 마음이 차분해져요.', '응, 이 시간이 되면 마음이 차분해져.')),
  b('neutral-14', 'day-wrap-up', undefined,
    t(F, 'warm', WARM, '오늘도 수고하셨어요.', '오늘도 수고했어.'),
    t(S, 'warm', WARM, '감사해요. 그 말씀 들으니 마음이 편해지네요.', '고마워. 그 말 들으니 마음이 편해지네.')),
  b('neutral-15', 'pre-bedtime', undefined,
    t(F, 'calm', CALM, '밤이 되니 집 안이 조용하네요.', '밤이 되니 집 안이 조용하네.'),
    t(S, 'calm', CALM, '그러게요. 차분한 분위기가 좋아요.', '그러게. 차분한 분위기가 좋아.')),
  b('neutral-16', 'pre-bedtime', undefined,
    t(F, 'calm', CALM, '슬슬 하루를 정리할 시간이에요.', '슬슬 하루를 정리할 시간이야.'),
    t(S, 'calm', CALM, '네, 오늘도 무사히 지나갔네요.', '응, 오늘도 무사히 지나갔네.')),
  b('neutral-17', 'bedtime', undefined,
    t(F, 'sleepy', CALM, '저는 이만 쉬어야겠어요. 좋은 밤 보내세요.', '나는 이만 쉬어야겠어. 좋은 밤 보내.'),
    t(S, 'warm', WARM, '네, 좋은 밤 되세요.', '응, 좋은 밤 돼.')),
  b('neutral-18', 'encounter', undefined,
    t(F, 'neutral', NEU, '아, 여기 계셨네요.', '아, 여기 있었네.'),
    t(S, 'neutral', NEU, '네, 방금 이쪽으로 왔어요.', '응, 방금 이쪽으로 왔어.')),
  b('neutral-19', 'encounter', undefined,
    t(F, 'neutral', NEU, '마주쳤네요. 잘 지내고 계세요?', '마주쳤네. 잘 지내고 있어?'),
    t(S, 'neutral', NEU, '네, 그럭저럭 편하게 지내요. 그쪽은요?', '응, 그럭저럭 편하게 지내. 너는?'),
    t(F, 'neutral', NEU, '저도 그래요.', '나도 그래.')),
  b('neutral-20', 'encounter', undefined,
    t(F, 'neutral', GLAD, '안녕하세요. 이쪽 방은 분위기가 좋네요.', '안녕. 이쪽 방은 분위기가 좋네.'),
    t(S, 'happy', GLAD, '그렇죠? 저도 이 방이 마음에 들어요.', '그렇지? 나도 이 방이 마음에 들어.')),
  b('neutral-21', 'casual-chat', undefined,
    t(F, 'calm', CALM, '이 방은 조용해서 생각하기 좋아요.', '이 방은 조용해서 생각하기 좋아.'),
    t(S, 'calm', CALM, '맞아요. 차분하게 있을 수 있어서 좋네요.', '맞아. 차분하게 있을 수 있어서 좋네.')),
  b('neutral-22', 'casual-chat', undefined,
    t(F, 'curious', NEU, '요즘 어떻게 지내세요?', '요즘 어떻게 지내?'),
    t(S, 'neutral', NEU, '평범하게 지내고 있어요. 별일은 없어요.', '평범하게 지내고 있어. 별일은 없어.'),
    t(F, 'calm', CALM, '평범한 게 제일 좋죠.', '평범한 게 제일 좋지.')),
  b('neutral-23', 'casual-chat', undefined,
    t(F, 'neutral', NEU, '여기서 보니 방이 참 아늑하네요.', '여기서 보니 방이 참 아늑하네.'),
    t(S, 'neutral', NEU, '네, 가구가 잘 어우러져 있어서 그런가 봐요.', '응, 가구가 잘 어우러져 있어서 그런가 봐.')),
  b('neutral-24', 'resting-together', undefined,
    t(F, 'calm', CALM, '잠깐 여기서 쉬어 가도 될까요?', '잠깐 여기서 쉬어 가도 될까?'),
    t(S, 'warm', WARM, '그럼요, 편하게 쉬세요.', '그럼, 편하게 쉬어.')),
  b('neutral-25', 'resting-together', undefined,
    t(F, 'calm', CALM, '가만히 있는 시간도 필요하죠.', '가만히 있는 시간도 필요하지.'),
    t(S, 'calm', CALM, '그렇죠. 잠깐 멈추면 생각이 정리돼요.', '그렇지. 잠깐 멈추면 생각이 정리돼.')),
  b('neutral-26', 'worried', undefined,
    t(F, 'worried', WARM, '표정이 조금 안 좋아 보여요. 무슨 일 있으세요?', '표정이 조금 안 좋아 보이는데, 무슨 일 있어?'),
    t(S, 'warm', WARM, '네, 괜찮아요. 걱정해 주셔서 고마워요.', '응, 괜찮아. 걱정해 줘서 고마워.')),
  b('neutral-27', 'comfort', undefined,
    t(F, 'gentle', WARM, '무리하지 않으셔도 돼요.', '무리하지 않아도 돼.'),
    t(S, 'warm', WARM, '네, 천천히 할게요. 그 말이 힘이 되네요.', '응, 천천히 할게. 그 말이 힘이 되네.')),
  b('neutral-28', 'compliment', undefined,
    t(F, 'warm', WARM, '오늘 표정이 밝아 보이네요.', '오늘 표정이 밝아 보이네.'),
    t(S, 'happy', SHY, '그런가요? 그렇게 봐 주셔서 기분이 좋아요.', '그래? 그렇게 봐 줘서 기분이 좋아.')),
  b('neutral-29', 'favor', undefined,
    t(F, 'neutral', NEU, '혹시 잠깐 시간 괜찮으세요?', '혹시 잠깐 시간 괜찮아?'),
    t(S, 'neutral', NEU, '네, 괜찮아요. 무슨 일이세요?', '응, 괜찮아. 무슨 일이야?')),
  b('neutral-30', 'gratitude', undefined,
    t(F, 'warm', WARM, '신경 써 주셔서 고마워요.', '신경 써 줘서 고마워.'),
    t(S, 'warm', WARM, '별말씀을요. 편하게 지내세요.', '별말을. 편하게 지내.')),
]

/** 친구 (30) */
export const FRIEND_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('friend-01', 'encounter', FRIEND,
    t(F, 'happy', GLAD, '어, 마침 잘 만났어요!', '어, 마침 잘 만났다!'),
    t(S, 'happy', GLAD, '반가워요. 뭐 하고 있었어요?', '반가워. 뭐 하고 있었어?'),
    t(F, 'neutral', NEU, '그냥 여기저기 둘러보고 있었어요.', '그냥 여기저기 둘러보고 있었어.')),
  b('friend-02', 'encounter', FRIEND,
    t(F, 'happy', GLAD, '여기서 만나다니 우연이네요.', '여기서 만나다니 우연이네.'),
    t(S, 'playful', PLAY, '그러게요. 덕분에 심심하지 않겠어요.', '그러게. 덕분에 심심하지 않겠다.')),
  b('friend-03', 'encounter', FRIEND,
    t(F, 'playful', PLAY, '어, 발견했어요!', '어, 발견!'),
    t(S, 'playful', PLAY, '들켰네요. 숨어 있던 건 아닌데.', '들켰네. 숨어 있던 건 아닌데.'),
    t(F, 'happy', GLAD, '그럼 같이 있어도 되죠?', '그럼 같이 있어도 되지?')),
  b('friend-04', 'morning-greeting', FRIEND,
    t(F, 'happy', GLAD, '좋은 아침이에요! 오늘은 뭐 하고 지낼 거예요?', '좋은 아침! 오늘은 뭐 하고 지낼 거야?'),
    t(S, 'neutral', NEU, '글쎄요, 천천히 정해 보려고요. 같이 정할래요?', '글쎄, 천천히 정해 보려고. 같이 정할래?')),
  b('friend-05', 'lunch', FRIEND,
    t(F, 'neutral', NEU, '점심 뭐 먹을지 벌써 고민이에요.', '점심 뭐 먹을지 벌써 고민이야.'),
    t(S, 'playful', PLAY, '저도요. 고르는 게 제일 어렵죠.', '나도. 고르는 게 제일 어렵지.'),
    t(F, 'happy', WARM, '그럼 같이 고민해요.', '그럼 같이 고민하자.')),
  b('friend-06', 'afternoon-chat', FRIEND,
    t(F, 'warm', WARM, '오후엔 괜히 이야기하고 싶어져요.', '오후엔 괜히 이야기하고 싶어져.'),
    t(S, 'warm', WARM, '좋아요, 무슨 이야기든 들어 줄게요.', '좋아, 무슨 이야기든 들어 줄게.')),
  b('friend-07', 'afternoon-chat', FRIEND,
    t(F, 'happy', GLAD, '잠깐 같이 돌아다녀 볼래요?', '잠깐 같이 돌아다녀 볼래?'),
    t(S, 'happy', GLAD, '좋아요. 어디부터 가 볼까요?', '좋아. 어디부터 가 볼까?'),
    t(F, 'playful', PLAY, '발길 닿는 대로 가요.', '발길 닿는 대로 가자.')),
  b('friend-08', 'snack', FRIEND,
    t(F, 'happy', WARM, '간식 같이 나눠 먹을래요?', '간식 같이 나눠 먹을래?'),
    t(S, 'happy', WARM, '좋죠. 혼자 먹는 것보다 맛있어요.', '좋지. 혼자 먹는 것보다 맛있어.')),
  b('friend-09', 'snack', FRIEND,
    t(F, 'playful', PLAY, '이런 시간엔 수다가 최고예요.', '이런 시간엔 수다가 최고야.'),
    t(S, 'happy', GLAD, '맞아요. 시간 가는 줄 몰라요.', '맞아. 시간 가는 줄 몰라.')),
  b('friend-10', 'casual-chat', FRIEND,
    t(F, 'curious', WARM, '요즘 기분은 어때요?', '요즘 기분은 어때?'),
    t(S, 'neutral', NEU, '나쁘지 않아요. 그쪽은요?', '나쁘지 않아. 너는?'),
    t(F, 'happy', WARM, '저도 괜찮아요. 다행이네요.', '나도 괜찮아. 다행이네.')),
  b('friend-11', 'casual-chat', FRIEND,
    t(F, 'curious', NEU, '오늘은 어떤 하루가 될 것 같아요?', '오늘은 어떤 하루가 될 것 같아?'),
    t(S, 'calm', CALM, '느긋한 하루요. 그러면 좋겠어요.', '느긋한 하루. 그러면 좋겠어.')),
  b('friend-12', 'casual-chat', FRIEND,
    t(F, 'warm', WARM, '얼굴 보니까 마음이 놓여요.', '얼굴 보니까 마음이 놓여.'),
    t(S, 'warm', WARM, '저도요. 편한 친구가 곁에 있어서 좋아요.', '나도. 편한 친구가 곁에 있어서 좋아.')),
  b('friend-13', 'casual-chat', FRIEND,
    t(F, 'calm', CALM, '말 안 해도 편한 사이라 다행이에요.', '말 안 해도 편한 사이라 다행이야.'),
    t(S, 'calm', CALM, '그러게요. 억지로 말 안 해도 되니까요.', '그러게. 억지로 말 안 해도 되니까.')),
  b('friend-14', 'teasing', FRIEND,
    t(F, 'playful', PLAY, '방금 표정 봤어요. 뭔가 신나 보이던데요?', '방금 표정 봤어. 뭔가 신나 보이던데?'),
    t(S, 'shy', SHY, '들켰네요. 아무 일도 아니에요.', '들켰네. 아무 일도 아니야.'),
    t(F, 'playful', PLAY, '아무 일도 아닌데 그렇게 웃어요?', '아무 일도 아닌데 그렇게 웃어?')),
  b('friend-15', 'teasing', FRIEND,
    t(F, 'playful', PLAY, '혹시 멍 때리고 있었죠?', '혹시 멍 때리고 있었지?'),
    t(S, 'playful', PLAY, '아니에요, 깊이 생각하고 있었어요.', '아니야, 깊이 생각하고 있었어.'),
    t(F, 'playful', PLAY, '깊이 멍 때린 거네요.', '깊이 멍 때린 거네.')),
  b('friend-16', 'teasing', FRIEND,
    t(F, 'playful', PLAY, '가만 보면 은근히 장난꾸러기예요.', '가만 보면 은근히 장난꾸러기야.'),
    t(S, 'playful', PLAY, '그런 말 하는 사람이 더하던데요.', '그런 말 하는 사람이 더하던데.'),
    t(F, 'happy', PLAY, '들켰네요, 하하.', '들켰네, 하하.')),
  b('friend-17', 'teasing', FRIEND,
    t(F, 'playful', PLAY, '오늘은 왠지 놀리고 싶은 표정이에요.', '오늘은 왠지 놀리고 싶은 표정이야.'),
    t(S, 'playful', PLAY, '그럼 저도 되돌려 줄게요.', '그럼 나도 되돌려 줄게.')),
  b('friend-18', 'resting-together', FRIEND,
    t(F, 'calm', WARM, '심심한데 같이 있을래요?', '심심한데 같이 있을래?'),
    t(S, 'calm', WARM, '좋아요. 가만히 이야기나 해요.', '좋아. 가만히 이야기나 하자.')),
  b('friend-19', 'resting-together', FRIEND,
    t(F, 'calm', CALM, '잠깐 쉬면서 수다 떨어요.', '잠깐 쉬면서 수다 떨자.'),
    t(S, 'happy', GLAD, '좋죠, 쉬는 시간엔 수다가 제격이에요.', '좋지, 쉬는 시간엔 수다가 제격이야.')),
  b('friend-20', 'worried', FRIEND,
    t(F, 'neutral', WARM, '요즘 고민이 하나 있는데 들어 줄래요?', '요즘 고민이 하나 있는데 들어 줄래?'),
    t(S, 'gentle', WARM, '그럼요, 편하게 말해 봐요.', '그럼, 편하게 말해 봐.'),
    t(F, 'neutral', NEU, '별건 아닌데, 오늘 뭘 할지 못 정하겠어요.', '별건 아닌데, 오늘 뭘 할지 못 정하겠어.'),
    t(S, 'warm', WARM, '그런 고민도 소중해요. 같이 생각해 봐요.', '그런 고민도 소중해. 같이 생각해 보자.')),
  b('friend-21', 'worried', FRIEND,
    t(F, 'worried', WARM, '표정이 조금 굳어 있어요. 무슨 생각해요?', '표정이 조금 굳어 있어. 무슨 생각해?'),
    t(S, 'neutral', NEU, '별건 아니에요. 그냥 이런저런 생각이요.', '별건 아니야. 그냥 이런저런 생각.'),
    t(F, 'gentle', WARM, '말하고 싶어지면 언제든 말해요.', '말하고 싶어지면 언제든 말해.')),
  b('friend-22', 'comfort', FRIEND,
    t(F, 'gentle', WARM, '힘내요. 옆에서 응원할게요.', '힘내. 옆에서 응원할게.'),
    t(S, 'warm', WARM, '고마워요. 그 말이 큰 힘이 돼요.', '고마워. 그 말이 큰 힘이 돼.')),
  b('friend-23', 'comfort', FRIEND,
    t(F, 'warm', WARM, '지금도 충분히 잘하고 있어요.', '지금도 충분히 잘하고 있어.'),
    t(S, 'calm', CALM, '그렇게 말해 주니 마음이 놓여요.', '그렇게 말해 주니 마음이 놓여.')),
  b('friend-24', 'compliment', FRIEND,
    t(F, 'warm', WARM, '오늘 분위기 좋아 보여요.', '오늘 분위기 좋아 보여.'),
    t(S, 'happy', SHY, '정말요? 기분이 좋아지네요.', '정말? 기분이 좋아지네.')),
  b('friend-25', 'compliment', FRIEND,
    t(F, 'warm', WARM, '웃는 얼굴 보니까 저도 기분이 좋아지네요.', '웃는 얼굴 보니까 나도 기분이 좋아지네.'),
    t(S, 'shy', SHY, '친구가 그렇게 말해 주니 쑥스럽네요.', '친구가 그렇게 말해 주니 쑥스럽네.')),
  b('friend-26', 'gratitude', FRIEND,
    t(F, 'warm', WARM, '친구로 있어 줘서 늘 고마워요.', '친구로 있어 줘서 늘 고마워.'),
    t(S, 'happy', WARM, '저도 그쪽 덕분에 즐거워요.', '나도 네 덕분에 즐거워.')),
  b('friend-27', 'favor', FRIEND,
    t(F, 'neutral', NEU, '부탁이 하나 있는데, 들어줄 수 있어요?', '부탁이 하나 있는데, 들어줄 수 있어?'),
    t(S, 'warm', WARM, '물론이죠. 뭐예요?', '물론이지. 뭔데?'),
    t(F, 'calm', CALM, '그냥 잠깐만 이야기 상대가 되어 줘요.', '그냥 잠깐만 이야기 상대가 되어 줘.')),
  b('friend-28', 'dinner', FRIEND,
    t(F, 'happy', WARM, '저녁 시간이네요. 같이 이야기하면서 쉬어요.', '저녁 시간이네. 같이 이야기하면서 쉬자.'),
    t(S, 'happy', WARM, '좋아요. 오늘 든 소소한 생각도 나눠요.', '좋아. 오늘 든 소소한 생각도 나누자.')),
  b('friend-29', 'day-wrap-up', FRIEND,
    t(F, 'curious', WARM, '오늘 하루 어땠어요?', '오늘 하루 어땠어?'),
    t(S, 'calm', CALM, '그럭저럭 괜찮았어요. 그쪽은요?', '그럭저럭 괜찮았어. 너는?'),
    t(F, 'happy', WARM, '저도 괜찮았어요. 이렇게 이야기하니 더 좋네요.', '나도 괜찮았어. 이렇게 이야기하니 더 좋네.')),
  b('friend-30', 'pre-bedtime', FRIEND,
    t(F, 'calm', CALM, '이제 슬슬 쉬어야 할 시간이네요.', '이제 슬슬 쉬어야 할 시간이네.'),
    t(S, 'warm', WARM, '네, 오늘도 같이 있어 줘서 즐거웠어요.', '응, 오늘도 같이 있어 줘서 즐거웠어.')),
]

/** 친밀한 관계 (30) — close, easy-going, frank, leaning on each other; no invented shared history. */
export const CLOSE_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('close-01', 'encounter', CLOSE,
    t(F, 'happy', GLAD, '어, 딱 좋은 때에 왔네요.', '어, 딱 좋은 때에 왔네.'),
    t(S, 'playful', PLAY, '그런 표정이면 뭔가 할 말 있는 거죠?', '그런 표정이면 뭔가 할 말 있는 거지?'),
    t(F, 'warm', WARM, '역시 눈치가 빠르네요. 그냥 같이 있고 싶었어요.', '역시 눈치가 빠르네. 그냥 같이 있고 싶었어.')),
  b('close-02', 'encounter', CLOSE,
    t(F, 'playful', PLAY, '얼굴만 봐도 오늘 기분을 알 것 같아요.', '얼굴만 봐도 오늘 기분을 알 것 같아.'),
    t(S, 'playful', PLAY, '진짜요? 어디 한번 맞혀 보세요.', '진짜? 어디 한번 맞혀 봐.'),
    t(F, 'calm', CALM, '느긋하고 평화로운 기분이죠?', '느긋하고 평화로운 기분이지?')),
  b('close-03', 'encounter', CLOSE,
    t(F, 'happy', GLAD, '어, 왔어요? 기다리진 않았지만 반가워요.', '어, 왔어? 기다리진 않았지만 반가워.'),
    t(S, 'playful', PLAY, '솔직해서 좋네요.', '솔직해서 좋네.')),
  b('close-04', 'morning-greeting', CLOSE,
    t(F, 'warm', WARM, '좋은 아침이에요. 오늘도 편하게 봐요.', '좋은 아침. 오늘도 편하게 보자.'),
    t(S, 'calm', CALM, '그래요. 편한 사이라 아침부터 마음이 가벼워요.', '그래. 편한 사이라 아침부터 마음이 가벼워.')),
  b('close-05', 'lunch', CLOSE,
    t(F, 'playful', PLAY, '점심 뭐 먹을지 제가 맞혀 볼까요?', '점심 뭐 먹을지 내가 맞혀 볼까?'),
    t(S, 'happy', GLAD, '맞혀 봐요. 기대되네요.', '맞혀 봐. 기대되네.'),
    t(F, 'playful', PLAY, '음, 그때그때 기분 따라 고르는 쪽이죠?', '음, 그때그때 기분 따라 고르는 쪽이지?')),
  b('close-06', 'afternoon-chat', CLOSE,
    t(F, 'calm', CALM, '오후엔 꼭 옆에서 쉬고 싶어져요.', '오후엔 꼭 옆에서 쉬고 싶어져.'),
    t(S, 'warm', WARM, '그럼 옆에서 쉬어요. 편하게요.', '그럼 옆에서 쉬어. 편하게.')),
  b('close-07', 'afternoon-chat', CLOSE,
    t(F, 'neutral', NEU, '솔직히 말하면 오늘은 좀 쉬고 싶어요.', '솔직히 말하면 오늘은 좀 쉬고 싶어.'),
    t(S, 'warm', WARM, '솔직해서 좋아요. 같이 쉬어요.', '솔직해서 좋아. 같이 쉬자.')),
  b('close-08', 'snack', CLOSE,
    t(F, 'playful', PLAY, '간식 앞에서는 표정이 다 드러나요.', '간식 앞에서는 표정이 다 드러나.'),
    t(S, 'shy', SHY, '그렇게 티가 나요? 부끄럽네요.', '그렇게 티가 나? 부끄럽네.'),
    t(F, 'playful', PLAY, '귀여운데요, 뭘.', '귀여운데, 뭘.')),
  b('close-09', 'casual-chat', CLOSE,
    t(F, 'calm', CALM, '우리는 말 없이 있어도 어색하지 않아서 좋아요.', '우리는 말 없이 있어도 어색하지 않아서 좋아.'),
    t(S, 'calm', CALM, '맞아요. 그게 제일 편해요.', '맞아. 그게 제일 편해.')),
  b('close-10', 'casual-chat', CLOSE,
    t(F, 'playful', PLAY, '무슨 생각하는지 대충 알 것 같은데요.', '무슨 생각하는지 대충 알 것 같은데.'),
    t(S, 'playful', PLAY, '그럼 말 안 해도 되겠네요.', '그럼 말 안 해도 되겠네.'),
    t(F, 'warm', WARM, '그래도 말해 주면 더 좋죠.', '그래도 말해 주면 더 좋지.')),
  b('close-11', 'casual-chat', CLOSE,
    t(F, 'neutral', NEU, '솔직히 오늘 조금 심심해요.', '솔직히 오늘 조금 심심해.'),
    t(S, 'warm', WARM, '잘 왔어요. 심심함은 같이 나누면 반이에요.', '잘 왔어. 심심함은 같이 나누면 반이야.')),
  b('close-12', 'casual-chat', CLOSE,
    t(F, 'warm', WARM, '편하게 말해도 되는 사람이 있어서 든든해요.', '편하게 말해도 되는 사람이 있어서 든든해.'),
    t(S, 'warm', WARM, '저도 그래요. 서로 그런 사이라 다행이에요.', '나도 그래. 서로 그런 사이라 다행이야.')),
  b('close-13', 'teasing', CLOSE,
    t(F, 'playful', PLAY, '지금 그 표정, 뭔가 숨기는 것 같은데요?', '지금 그 표정, 뭔가 숨기는 것 같은데?'),
    t(S, 'playful', PLAY, '숨기긴요. 그냥 딴생각했어요.', '숨기긴. 그냥 딴생각했어.'),
    t(F, 'playful', PLAY, '딴생각이 뭔지가 궁금한 건데요.', '딴생각이 뭔지가 궁금한 건데.')),
  b('close-14', 'teasing', CLOSE,
    t(F, 'playful', PLAY, '고집부리는 얼굴이네요. 알아요, 그 얼굴.', '고집부리는 얼굴이네. 알아, 그 얼굴.'),
    t(S, 'playful', PLAY, '고집이 아니라 소신이라고 해 줘요.', '고집이 아니라 소신이라고 해 줘.')),
  b('close-15', 'teasing', CLOSE,
    t(F, 'playful', PLAY, '제일 편한 사람 앞에서만 그렇게 풀어지는 거죠?', '제일 편한 사람 앞에서만 그렇게 풀어지는 거지?'),
    t(S, 'playful', PLAY, '비밀이에요. 대답하면 자랑이 되니까요.', '비밀이야. 대답하면 자랑이 되니까.')),
  b('close-16', 'teasing', CLOSE,
    t(F, 'playful', PLAY, '가끔 너무 솔직해서 웃겨요.', '가끔 너무 솔직해서 웃겨.'),
    t(S, 'playful', PLAY, '그게 매력이라고 해 줘요.', '그게 매력이라고 해 줘.'),
    t(F, 'happy', PLAY, '인정할게요. 매력 맞아요.', '인정할게. 매력 맞아.')),
  b('close-17', 'resting-together', CLOSE,
    t(F, 'calm', CALM, '그냥 옆에 있어 줘요. 말은 안 해도 돼요.', '그냥 옆에 있어 줘. 말은 안 해도 돼.'),
    t(S, 'calm', CALM, '그럼 조용히 옆에 있을게요.', '그럼 조용히 옆에 있을게.')),
  b('close-18', 'resting-together', CLOSE,
    t(F, 'neutral', NEU, '쉬는 동안 아무 얘기나 해도 돼요?', '쉬는 동안 아무 얘기나 해도 돼?'),
    t(S, 'happy', WARM, '물론이죠. 아무 얘기나 좋아요.', '물론이지. 아무 얘기나 좋아.')),
  b('close-19', 'worried', CLOSE,
    t(F, 'worried', WARM, '오늘은 표정이 조금 무거워 보여요. 괜찮아요?', '오늘은 표정이 조금 무거워 보여. 괜찮아?'),
    t(S, 'calm', CALM, '조금 지쳤어요. 티 났네요.', '조금 지쳤어. 티 났네.'),
    t(F, 'gentle', WARM, '티 나죠. 이럴 땐 기대도 돼요.', '티 나지. 이럴 땐 기대도 돼.')),
  b('close-20', 'worried', CLOSE,
    t(F, 'gentle', WARM, '힘들면 힘들다고 말해도 돼요.', '힘들면 힘들다고 말해도 돼.'),
    t(S, 'warm', WARM, '고마워요. 그 말 들으니 벌써 낫는 것 같아요.', '고마워. 그 말 들으니 벌써 낫는 것 같아.')),
  b('close-21', 'worried', CLOSE,
    t(F, 'gentle', WARM, '혼자 끙끙대지 말아요. 저 여기 있어요.', '혼자 끙끙대지 마. 나 여기 있어.'),
    t(S, 'warm', WARM, '네, 그럴게요. 옆에 있어 줘서 든든해요.', '응, 그럴게. 옆에 있어 줘서 든든해.')),
  b('close-22', 'comfort', CLOSE,
    t(F, 'warm', WARM, '괜찮아요. 잘하고 있어요, 정말로요.', '괜찮아. 잘하고 있어, 정말로.'),
    t(S, 'calm', CALM, '솔직한 말이라 더 믿음이 가요.', '솔직한 말이라 더 믿음이 가.')),
  b('close-23', 'comfort', CLOSE,
    t(F, 'gentle', WARM, '무슨 일이든 같이 생각해 볼게요.', '무슨 일이든 같이 생각해 볼게.'),
    t(S, 'warm', WARM, '그 말이면 충분해요. 벌써 마음이 가벼워요.', '그 말이면 충분해. 벌써 마음이 가벼워.')),
  b('close-24', 'comfort', CLOSE,
    t(F, 'gentle', WARM, '지친 날엔 그냥 쉬어요. 제가 옆에 있을게요.', '지친 날엔 그냥 쉬어. 내가 옆에 있을게.'),
    t(S, 'warm', WARM, '네, 그럴게요. 고마워요.', '응, 그럴게. 고마워.')),
  b('close-25', 'compliment', CLOSE,
    t(F, 'warm', WARM, '이야기하다 보면 마음이 가벼워져요.', '이야기하다 보면 마음이 가벼워져.'),
    t(S, 'shy', SHY, '그런 말은 갑자기 들으면 쑥스러워요.', '그런 말은 갑자기 들으면 쑥스러워.'),
    t(F, 'warm', WARM, '솔직하게 말한 건데요.', '솔직하게 말한 건데.')),
  b('close-26', 'compliment', CLOSE,
    t(F, 'warm', WARM, '웃을 때 보면 기분이 다 좋아 보여요.', '웃을 때 보면 기분이 다 좋아 보여.'),
    t(S, 'shy', SHY, '친한 사이라도 칭찬은 쑥스러워요.', '친한 사이라도 칭찬은 쑥스러워.')),
  b('close-27', 'gratitude', CLOSE,
    t(F, 'warm', WARM, '늘 편하게 대해 줘서 고마워요.', '늘 편하게 대해 줘서 고마워.'),
    t(S, 'warm', WARM, '저야말로요. 그 덕에 저도 편해요.', '나야말로. 그 덕에 나도 편해.')),
  b('close-28', 'favor', CLOSE,
    t(F, 'neutral', NEU, '부탁 하나만 해도 될까요? 그쪽한테만 하는 부탁이에요.', '부탁 하나만 해도 될까? 너한테만 하는 부탁이야.'),
    t(S, 'warm', WARM, '말해 봐요. 들을 준비 됐어요.', '말해 봐. 들을 준비 됐어.'),
    t(F, 'calm', CALM, '잠깐만 옆에서 이야기 들어 줘요.', '잠깐만 옆에서 이야기 들어 줘.')),
  b('close-29', 'dinner', CLOSE,
    t(F, 'warm', WARM, '저녁엔 역시 편한 사람이랑 있는 게 좋아요.', '저녁엔 역시 편한 사람이랑 있는 게 좋아.'),
    t(S, 'calm', CALM, '동의해요. 하루가 차분하게 마무리되잖아요.', '동의해. 하루가 차분하게 마무리되잖아.')),
  b('close-30', 'day-wrap-up', CLOSE,
    t(F, 'warm', WARM, '오늘도 곁에 있어 줘서 든든했어요.', '오늘도 곁에 있어 줘서 든든했어.'),
    t(S, 'warm', WARM, '저도요. 이렇게 하루가 끝나니 좋네요.', '나도. 이렇게 하루가 끝나니 좋네.')),
]

const FAMILY: RelationshipType[] = ['family']
const RIVAL: RelationshipType[] = ['rival']
const AWKWARD: RelationshipType[] = ['awkward']
const RIVALRY = ['직설']
const AWK = ['어색', '조심']

/**
 * 가족 (30). Warm and everyday, never assuming a specific blood relation, age
 * order or address term (no 형/누나/언니/오빠/동생/엄마/아빠) — the family flavor
 * comes from ease and small, unprompted care, not from a role.
 */
export const FAMILY_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('family-01', 'morning-greeting', FAMILY,
    t(F, 'warm', WARM, '일어났어요? 오늘도 편하게 시작해요.', '일어났어? 오늘도 편하게 시작하자.'),
    t(S, 'calm', CALM, '네, 잘 잤어요. 집이라 그런지 편히 잤네요.', '응, 잘 잤어. 집이라 그런지 편히 잤어.')),
  b('family-02', 'morning-greeting', FAMILY,
    t(F, 'calm', CALM, '오늘도 무리하지 말고 편하게 지내요.', '오늘도 무리하지 말고 편하게 지내.'),
    t(S, 'warm', WARM, '그렇게 말해 주니 마음이 편해요. 그쪽도요.', '그렇게 말해 주니 마음이 편해. 너도.')),
  b('family-03', 'wake-up', FAMILY,
    t(F, 'gentle', WARM, '더 자도 괜찮아요. 서두를 필요 없어요.', '더 자도 괜찮아. 서두를 필요 없어.'),
    t(S, 'sleepy', CALM, '그럼 조금만 더 있을게요.', '그럼 조금만 더 있을게.')),
  b('family-04', 'breakfast', FAMILY,
    t(F, 'neutral', WARM, '아침 챙겨 먹었어요?', '아침 챙겨 먹었어?'),
    t(S, 'neutral', NEU, '아직요. 뭐 먹을지 같이 골라 줄래요?', '아직. 뭐 먹을지 같이 골라 줄래?')),
  b('family-05', 'lunch', FAMILY,
    t(F, 'neutral', NEU, '점심은 집에서 먹을 거예요?', '점심은 집에서 먹을 거야?'),
    t(S, 'neutral', NEU, '네, 오늘은 그럴 것 같아요.', '응, 오늘은 그럴 것 같아.')),
  b('family-06', 'afternoon-chat', FAMILY,
    t(F, 'calm', CALM, '집 안이 조용하니까 마음이 놓여요.', '집 안이 조용하니까 마음이 놓여.'),
    t(S, 'calm', CALM, '맞아요. 이런 시간이 은근히 소중해요.', '맞아. 이런 시간이 은근히 소중해.')),
  b('family-07', 'afternoon-chat', FAMILY,
    t(F, 'neutral', NEU, '오후엔 딱히 할 일이 없어서 여유로워요.', '오후엔 딱히 할 일이 없어서 여유로워.'),
    t(S, 'warm', WARM, '그럼 잠깐 같이 있어요.', '그럼 잠깐 같이 있자.')),
  b('family-08', 'snack', FAMILY,
    t(F, 'happy', WARM, '간식 좀 나눠 먹을래요?', '간식 좀 나눠 먹을래?'),
    t(S, 'happy', WARM, '좋아요. 같이 먹으면 더 맛있죠.', '좋아. 같이 먹으면 더 맛있지.')),
  b('family-09', 'snack', FAMILY,
    t(F, 'calm', WARM, '이거 하나 먹을래요? 넉넉히 있어요.', '이거 하나 먹을래? 넉넉히 있어.'),
    t(S, 'warm', WARM, '고마워요. 챙겨 주는 거 항상 고맙네요.', '고마워. 챙겨 주는 거 항상 고맙네.')),
  b('family-10', 'casual-chat', FAMILY,
    t(F, 'calm', CALM, '집이라 그런지 말 안 해도 편해요.', '집이라 그런지 말 안 해도 편해.'),
    t(S, 'calm', CALM, '그러게요. 이게 가족이라는 거겠죠.', '그러게. 이게 가족이라는 거겠지.')),
  b('family-11', 'casual-chat', FAMILY,
    t(F, 'curious', WARM, '오늘 별일 없었어요?', '오늘 별일 없었어?'),
    t(S, 'neutral', NEU, '네, 그냥 평범했어요. 그쪽은요?', '응, 그냥 평범했어. 너는?'),
    t(F, 'calm', WARM, '저도 평범했어요. 다행이에요.', '나도 평범했어. 다행이야.')),
  b('family-12', 'casual-chat', FAMILY,
    t(F, 'warm', WARM, '같이 사는 사람이 있다는 게 든든해요.', '같이 지내는 사람이 있다는 게 든든해.'),
    t(S, 'warm', WARM, '저도 그래요. 집이 더 집 같아져요.', '나도 그래. 집이 더 집 같아져.')),
  b('family-13', 'teasing', FAMILY,
    t(F, 'playful', PLAY, '방금 그 표정, 저 알아요.', '방금 그 표정, 나 알아.'),
    t(S, 'playful', PLAY, '무슨 표정인데요?', '무슨 표정인데?'),
    t(F, 'playful', PLAY, '뭔가 미루고 있는 표정이요.', '뭔가 미루고 있는 표정.'),
    t(S, 'playful', PLAY, '들켰네요.', '들켰네.')),
  b('family-14', 'teasing', FAMILY,
    t(F, 'playful', PLAY, '또 그러고 있네요.', '또 그러고 있네.'),
    t(S, 'playful', PLAY, '뭘요, 그냥 쉬는 거예요.', '뭘, 그냥 쉬는 거야.'),
    t(F, 'happy', PLAY, '알겠어요, 편하게 쉬어요.', '알겠어, 편하게 쉬어.')),
  b('family-15', 'teasing', FAMILY,
    t(F, 'playful', PLAY, '가끔 보면 은근히 고집 있어요.', '가끔 보면 은근히 고집 있어.'),
    t(S, 'playful', PLAY, '그쪽도 만만치 않은데요.', '너도 만만치 않은데.')),
  b('family-16', 'resting-together', FAMILY,
    t(F, 'calm', CALM, '잠깐 같이 앉아 있을래요?', '잠깐 같이 앉아 있을래?'),
    t(S, 'calm', CALM, '좋아요. 딱히 할 말 없어도 괜찮죠.', '좋아. 딱히 할 말 없어도 괜찮지.')),
  b('family-17', 'resting-together', FAMILY,
    t(F, 'calm', CALM, '이렇게 가만히 있는 시간도 필요해요.', '이렇게 가만히 있는 시간도 필요해.'),
    t(S, 'calm', CALM, '맞아요, 집에서는 이게 제일 좋아요.', '맞아, 집에서는 이게 제일 좋아.')),
  b('family-18', 'worried', FAMILY,
    t(F, 'worried', WARM, '오늘 좀 피곤해 보여요. 괜찮아요?', '오늘 좀 피곤해 보여. 괜찮아?'),
    t(S, 'calm', CALM, '괜찮아요. 조금 쉬면 나아질 거예요.', '괜찮아. 조금 쉬면 나아질 거야.'),
    t(F, 'gentle', WARM, '그럼 오늘은 일찍 쉬어요.', '그럼 오늘은 일찍 쉬어.')),
  b('family-19', 'worried', FAMILY,
    t(F, 'gentle', WARM, '힘든 일 있으면 말해요. 들어줄게요.', '힘든 일 있으면 말해. 들어줄게.'),
    t(S, 'warm', WARM, '고마워요. 그냥 알아주는 것만으로 든든해요.', '고마워. 그냥 알아주는 것만으로 든든해.')),
  b('family-20', 'comfort', FAMILY,
    t(F, 'gentle', WARM, '집에서는 편하게 있어도 돼요.', '집에서는 편하게 있어도 돼.'),
    t(S, 'calm', CALM, '그 말이 제일 편하게 들려요.', '그 말이 제일 편하게 들려.')),
  b('family-21', 'comfort', FAMILY,
    t(F, 'warm', WARM, '오늘 하루 애썼어요.', '오늘 하루 애썼어.'),
    t(S, 'warm', WARM, '그쪽도요. 이렇게 챙겨 주니 든든해요.', '너도. 이렇게 챙겨 주니 든든해.')),
  b('family-22', 'compliment', FAMILY,
    t(F, 'warm', WARM, '오늘따라 표정이 편안해 보여요.', '오늘따라 표정이 편안해 보여.'),
    t(S, 'happy', WARM, '집에 있으니까 그런가 봐요.', '집에 있으니까 그런가 봐.')),
  b('family-23', 'favor', FAMILY,
    t(F, 'neutral', NEU, '잠깐 손 좀 빌려도 될까요?', '잠깐 손 좀 빌려도 될까?'),
    t(S, 'warm', WARM, '그럼요, 뭐 도와줄까요?', '그럼, 뭐 도와줄까?'),
    t(F, 'calm', NEU, '별건 아니고, 잠깐 같이 봐 줬으면 해서요.', '별건 아니고, 잠깐 같이 봐 줬으면 해서.')),
  b('family-24', 'gratitude', FAMILY,
    t(F, 'warm', WARM, '평소에 챙겨 줘서 고마워요.', '평소에 챙겨 줘서 고마워.'),
    t(S, 'warm', WARM, '가족끼리 그런 거 당연하죠.', '가족끼리 그런 거 당연하지.')),
  b('family-25', 'gratitude', FAMILY,
    t(F, 'warm', WARM, '같이 지내 줘서 고마워요.', '같이 지내 줘서 고마워.'),
    t(S, 'calm', CALM, '저도 마찬가지예요. 편한 사람이 있어서 좋아요.', '나도 마찬가지야. 편한 사람이 있어서 좋아.')),
  b('family-26', 'dinner', FAMILY,
    t(F, 'happy', WARM, '저녁 같이 먹을래요?', '저녁 같이 먹을래?'),
    t(S, 'happy', WARM, '좋아요. 오랜만에 같이 먹어요.', '좋아. 오랜만에 같이 먹자.')),
  b('family-27', 'day-wrap-up', FAMILY,
    t(F, 'calm', WARM, '오늘은 어떻게 보냈어요?', '오늘은 어떻게 보냈어?'),
    t(S, 'calm', CALM, '무난했어요. 지금은 편안하고요.', '무난했어. 지금은 편안하고.'),
    t(F, 'warm', WARM, '그럼 됐어요. 오늘도 수고했어요.', '그럼 됐어. 오늘도 수고했어.')),
  b('family-28', 'pre-bedtime', FAMILY,
    t(F, 'calm', CALM, '슬슬 정리하고 쉴 시간이네요.', '슬슬 정리하고 쉴 시간이네.'),
    t(S, 'calm', CALM, '그러게요. 오늘도 무사히 지나갔어요.', '그러게. 오늘도 무사히 지나갔어.')),
  b('family-29', 'bedtime', FAMILY,
    t(F, 'sleepy', WARM, '저는 먼저 쉴게요. 잘 자요.', '나는 먼저 쉴게. 잘 자.'),
    t(S, 'warm', WARM, '네, 잘 자요. 내일 봐요.', '응, 잘 자. 내일 봐.')),
  b('family-30', 'casual-chat', FAMILY,
    t(F, 'calm', CALM, '이렇게 편하게 지낼 수 있는 사이라 좋아요.', '이렇게 편하게 지낼 수 있는 사이라 좋아.'),
    t(S, 'warm', WARM, '맞아요. 같이 지내는 게 자연스러워요.', '맞아. 같이 지내는 게 자연스러워.')),
]

/**
 * 라이벌 (30). Competitive but respectful; never states a win/loss that
 * never happened — the competition stays a mood (승부욕, 도발, 인정), not a
 * scored event.
 */
export const RIVAL_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('rival-01', 'encounter', RIVAL,
    t(F, 'competitive', RIVALRY, '또 마주쳤네요.', '또 마주쳤네.'),
    t(S, 'competitive', RIVALRY, '그러게요. 신경 쓰이는 상대라 그런가 봐요.', '그러게. 신경 쓰이는 상대라 그런가 봐.')),
  b('rival-02', 'encounter', RIVAL,
    t(F, 'competitive', RIVALRY, '오늘도 지지 않을 준비 됐어요?', '오늘도 지지 않을 준비 됐어?'),
    t(S, 'competitive', RIVALRY, '그 말 그대로 돌려드릴게요.', '그 말 그대로 돌려줄게.')),
  b('rival-03', 'morning-greeting', RIVAL,
    t(F, 'neutral', RIVALRY, '아침부터 컨디션이 좋아 보이네요.', '아침부터 컨디션이 좋아 보이네.'),
    t(S, 'competitive', RIVALRY, '그쪽도 만만치 않아 보이는데요.', '너도 만만치 않아 보이는데.')),
  b('rival-04', 'afternoon-chat', RIVAL,
    t(F, 'competitive', RIVALRY, '오늘은 왠지 지고 싶지 않은 기분이에요.', '오늘은 왠지 지고 싶지 않은 기분이야.'),
    t(S, 'playful', RIVALRY, '그 기분, 저도 똑같아요.', '그 기분, 나도 똑같아.')),
  b('rival-05', 'casual-chat', RIVAL,
    t(F, 'competitive', RIVALRY, '솔직히 그쪽한테는 지고 싶지 않아요.', '솔직히 너한테는 지고 싶지 않아.'),
    t(S, 'competitive', RIVALRY, '저도 마찬가지예요. 그래서 재밌는 거죠.', '나도 마찬가지야. 그래서 재밌는 거지.')),
  b('rival-06', 'casual-chat', RIVAL,
    t(F, 'neutral', RIVALRY, '가끔은 그쪽이 뭘 하는지 궁금해요.', '가끔은 네가 뭘 하는지 궁금해.'),
    t(S, 'playful', RIVALRY, '신경 쓰인다는 뜻이죠?', '신경 쓰인다는 뜻이지?'),
    t(F, 'competitive', RIVALRY, '그냥 상황 파악이에요.', '그냥 상황 파악이야.')),
  b('rival-07', 'teasing', RIVAL,
    t(F, 'playful', RIVALRY, '그렇게 여유 부려도 되는 거예요?', '그렇게 여유 부려도 되는 거야?'),
    t(S, 'playful', RIVALRY, '여유가 아니라 자신감이에요.', '여유가 아니라 자신감이야.'),
    t(F, 'competitive', RIVALRY, '두고 보죠.', '두고 보죠, 아니 두고 보자.')),
  b('rival-08', 'teasing', RIVAL,
    t(F, 'playful', RIVALRY, '오늘따라 자신만만하네요.', '오늘따라 자신만만하네.'),
    t(S, 'competitive', RIVALRY, '근거 없는 자신감은 아니에요.', '근거 없는 자신감은 아니야.')),
  b('rival-09', 'compliment', RIVAL,
    t(F, 'neutral', RIVALRY, '인정할 건 인정할게요. 그쪽 그 부분은 잘해요.', '인정할 건 인정할게. 너 그 부분은 잘해.'),
    t(S, 'happy', RIVALRY, '뜻밖이네요. 그쪽도 그 정도면 괜찮아요.', '뜻밖이네. 너도 그 정도면 괜찮아.')),
  b('rival-10', 'compliment', RIVAL,
    t(F, 'neutral', RIVALRY, '경쟁 상대로 나쁘지 않아요.', '경쟁 상대로 나쁘지 않아.'),
    t(S, 'competitive', RIVALRY, '그 말은 칭찬으로 들어 둘게요.', '그 말은 칭찬으로 들어 둘게.')),
  b('rival-11', 'resting-together', RIVAL,
    t(F, 'neutral', RIVALRY, '잠깐은 경쟁 안 하고 쉬어도 되죠?', '잠깐은 경쟁 안 하고 쉬어도 되지?'),
    t(S, 'calm', RIVALRY, '그 정도 휴전은 좋아요.', '그 정도 휴전은 좋아.')),
  b('rival-12', 'snack', RIVAL,
    t(F, 'competitive', RIVALRY, '이 간식, 저 먼저 봤어요.', '이 간식, 내가 먼저 봤어.'),
    t(S, 'competitive', RIVALRY, '먼저 본다고 임자는 아니죠.', '먼저 본다고 임자는 아니지.'),
    t(F, 'playful', RIVALRY, '그럼 나눠 먹죠.', '그럼 나눠 먹자.')),
  b('rival-13', 'worried', RIVAL,
    t(F, 'worried', RIVALRY, '오늘은 평소보다 기운이 없어 보이는데요.', '오늘은 평소보다 기운이 없어 보이는데.'),
    t(S, 'neutral', RIVALRY, '컨디션 관리도 실력이니까요. 걱정 마세요.', '컨디션 관리도 실력이니까. 걱정 마.'),
    t(F, 'neutral', RIVALRY, '그런 걸로 지면 재미없잖아요.', '그런 걸로 지면 재미없잖아.')),
  b('rival-14', 'comfort', RIVAL,
    t(F, 'neutral', RIVALRY, '오늘 컨디션 안 좋아 보이던데, 무리하지 말아요.', '오늘 컨디션 안 좋아 보이던데, 무리하지 마.'),
    t(S, 'calm', RIVALRY, '걱정이에요, 아니면 그냥 견제예요?', '걱정이야, 아니면 그냥 견제야?'),
    t(F, 'playful', RIVALRY, '둘 다요.', '둘 다.')),
  b('rival-15', 'gratitude', RIVAL,
    t(F, 'neutral', RIVALRY, '자극이 돼서 고마워요. 솔직히요.', '자극이 돼서 고마워. 솔직히.'),
    t(S, 'competitive', RIVALRY, '저도 그래요. 그쪽 덕분에 느슨해지지 않아요.', '나도 그래. 너 덕분에 느슨해지지 않아.')),
  b('rival-16', 'casual-chat', RIVAL,
    t(F, 'neutral', RIVALRY, '가끔은 우리가 잘 맞는다는 생각도 들어요.', '가끔은 우리가 잘 맞는다는 생각도 들어.'),
    t(S, 'competitive', RIVALRY, '경쟁이 잘 맞는다는 뜻이라면 동의해요.', '경쟁이 잘 맞는다는 뜻이라면 동의해.')),
  b('rival-17', 'casual-chat', RIVAL,
    t(F, 'competitive', RIVALRY, '솔직히 그쪽이 없으면 좀 심심할 것 같아요.', '솔직히 네가 없으면 좀 심심할 것 같아.'),
    t(S, 'playful', RIVALRY, '그 말, 은근히 기분 좋네요.', '그 말, 은근히 기분 좋네.')),
  b('rival-18', 'day-wrap-up', RIVAL,
    t(F, 'neutral', RIVALRY, '오늘 하루, 그쪽은 어떻게 보냈어요?', '오늘 하루, 너는 어떻게 보냈어?'),
    t(S, 'competitive', RIVALRY, '나쁘지 않았어요. 내일은 더 잘할 거예요.', '나쁘지 않았어. 내일은 더 잘할 거야.'),
    t(F, 'competitive', RIVALRY, '그 말, 저도 그대로예요.', '그 말, 나도 그대로야.')),
  b('rival-19', 'encounter', RIVAL,
    t(F, 'neutral', RIVALRY, '오늘은 왠지 긴장되네요.', '오늘은 왠지 긴장되네.'),
    t(S, 'competitive', RIVALRY, '저도요. 그쪽이 있으면 늘 그래요.', '나도. 너 있으면 늘 그래.')),
  b('rival-20', 'teasing', RIVAL,
    t(F, 'playful', RIVALRY, '자신 있어 보이는 그 표정, 부담스러운데요.', '자신 있어 보이는 그 표정, 부담스러운데.'),
    t(S, 'playful', RIVALRY, '부담 가지라고 짓는 표정이에요.', '부담 가지라고 짓는 표정이야.')),
  b('rival-21', 'teasing', RIVAL,
    t(F, 'playful', RIVALRY, '방심하는 거 아니죠?', '방심하는 거 아니지?'),
    t(S, 'competitive', RIVALRY, '방심할 상대가 아니라서요.', '방심할 상대가 아니라서.')),
  b('rival-22', 'compliment', RIVAL,
    t(F, 'neutral', RIVALRY, '솔직히 그쪽 덕분에 저도 더 나아지는 것 같아요.', '솔직히 너 덕분에 나도 더 나아지는 것 같아.'),
    t(S, 'happy', RIVALRY, '그 말은 순순히 받을게요. 저도 같은 마음이에요.', '그 말은 순순히 받을게. 나도 같은 마음이야.')),
  b('rival-23', 'casual-chat', RIVAL,
    t(F, 'competitive', RIVALRY, '오늘은 어떤 식으로 이겨 볼까 고민 중이에요.', '오늘은 어떤 식으로 이겨 볼까 고민 중이야.'),
    t(S, 'playful', RIVALRY, '고민하는 동안 저는 이미 준비 끝났어요.', '고민하는 동안 나는 이미 준비 끝났어.')),
  b('rival-24', 'casual-chat', RIVAL,
    t(F, 'neutral', RIVALRY, '그쪽이랑 있으면 긴장을 놓을 수가 없어요.', '너랑 있으면 긴장을 놓을 수가 없어.'),
    t(S, 'competitive', RIVALRY, '그게 저의 존재 이유죠.', '그게 내 존재 이유지.')),
  b('rival-25', 'favor', RIVAL,
    t(F, 'neutral', RIVALRY, '이번 한 번만 도와줄 수 있어요?', '이번 한 번만 도와줄 수 있어?'),
    t(S, 'playful', RIVALRY, '빚으로 남겨 둘게요.', '빚으로 남겨 둘게.'),
    t(F, 'neutral', RIVALRY, '그 정도는 봐줄게요.', '그 정도는 봐줄게.')),
  b('rival-26', 'gratitude', RIVAL,
    t(F, 'neutral', RIVALRY, '이번엔 도와줘서 고마워요.', '이번엔 도와줘서 고마워.'),
    t(S, 'competitive', RIVALRY, '다음엔 다시 대결이에요.', '다음엔 다시 대결이야.')),
  b('rival-27', 'resting-together', RIVAL,
    t(F, 'calm', RIVALRY, '이럴 때 보면 그쪽도 그냥 사람이네요.', '이럴 때 보면 너도 그냥 사람이네.'),
    t(S, 'playful', RIVALRY, '그쪽도 마찬가지예요.', '너도 마찬가지야.')),
  b('rival-28', 'pre-bedtime', RIVAL,
    t(F, 'neutral', RIVALRY, '오늘은 여기까지 하죠.', '오늘은 여기까지 하자.'),
    t(S, 'competitive', RIVALRY, '좋아요. 내일 다시 겨뤄요.', '좋아. 내일 다시 겨루자.')),
  b('rival-29', 'bedtime', RIVAL,
    t(F, 'neutral', RIVALRY, '오늘 하루도 나름 치열했네요.', '오늘 하루도 나름 치열했네.'),
    t(S, 'competitive', RIVALRY, '그러게요. 내일도 그럴 거예요.', '그러게. 내일도 그럴 거야.')),
  b('rival-30', 'casual-chat', RIVAL,
    t(F, 'neutral', RIVALRY, '이상하게 그쪽이랑 있으면 힘이 나요.', '이상하게 너랑 있으면 힘이 나.'),
    t(S, 'competitive', RIVALRY, '자극이 된다는 뜻이면 저도 동감이에요.', '자극이 된다는 뜻이면 나도 동감이야.')),
]

/**
 * 어색한 사이 (30). Cautious and gradually easing, deliberately NOT drifting
 * romantic — short exchanges, careful pauses, small steps toward comfort.
 */
export const AWKWARD_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('awkward-01', 'encounter', AWKWARD,
    t(F, 'shy', AWK, '아… 안녕하세요.', '아… 안녕.'),
    t(S, 'shy', AWK, '네, 안녕하세요.', '어, 안녕.')),
  b('awkward-02', 'encounter', AWKWARD,
    t(F, 'shy', AWK, '어… 이쪽에 계셨군요.', '어… 이쪽에 있었구나.'),
    t(S, 'shy', AWK, '네… 방금 왔어요.', '응… 방금 왔어.')),
  b('awkward-03', 'morning-greeting', AWKWARD,
    t(F, 'shy', AWK, '저… 좋은 아침이에요.', '저… 좋은 아침.'),
    t(S, 'shy', AWK, '아, 네. 좋은 아침이에요.', '어, 응. 좋은 아침.')),
  b('awkward-04', 'casual-chat', AWKWARD,
    t(F, 'shy', AWK, '저기… 요즘 잘 지내세요?', '저기… 요즘 잘 지내?'),
    t(S, 'shy', AWK, '네, 그럭저럭요. 그쪽은요?', '어, 그럭저럭. 너는?'),
    t(F, 'shy', AWK, '저도 비슷해요. 조금씩 편해지는 것 같아요.', '나도 비슷해. 조금씩 편해지는 것 같아.')),
  b('awkward-05', 'casual-chat', AWKWARD,
    t(F, 'neutral', NEU, '날씨가 좋네요.', '날씨가 좋네.'),
    t(S, 'shy', AWK, '그러게요… 산책하기 좋을 것 같아요.', '그러게… 산책하기 좋을 것 같아.')),
  b('awkward-06', 'casual-chat', AWKWARD,
    t(F, 'shy', AWK, '음… 딱히 할 말은 없는데, 그냥요.', '음… 딱히 할 말은 없는데, 그냥.'),
    t(S, 'shy', AWK, '괜찮아요. 저도 그럴 때 있어요.', '괜찮아. 나도 그럴 때 있어.')),
  b('awkward-07', 'casual-chat', AWKWARD,
    t(F, 'neutral', NEU, '이 방, 마음에 드세요?', '이 방, 마음에 들어?'),
    t(S, 'shy', AWK, '네, 편안한 것 같아요.', '어, 편안한 것 같아.')),
  b('awkward-08', 'afternoon-chat', AWKWARD,
    t(F, 'shy', AWK, '조용하네요.', '조용하네.'),
    t(S, 'shy', AWK, '네… 이런 침묵도 나쁘지 않아요.', '응… 이런 침묵도 나쁘지 않아.')),
  b('awkward-09', 'afternoon-chat', AWKWARD,
    t(F, 'shy', AWK, '이렇게 이야기하는 것도 조금씩 편해지는 것 같아요.', '이렇게 이야기하는 것도 조금씩 편해지는 것 같아.'),
    t(S, 'shy', AWK, '저도요. 처음보다는 나아요.', '나도. 처음보다는 나아.')),
  b('awkward-10', 'snack', AWKWARD,
    t(F, 'shy', AWK, '이거… 드실래요?', '이거… 먹을래?'),
    t(S, 'shy', AWK, '아, 감사해요.', '아, 고마워.')),
  b('awkward-11', 'teasing', AWKWARD,
    t(F, 'shy', AWK, '그, 표정이 좀 편해지신 것 같아요.', '그, 표정이 좀 편해진 것 같아.'),
    t(S, 'shy', AWK, '그런가요? 조금씩요.', '그런가? 조금씩.')),
  b('awkward-12', 'resting-together', AWKWARD,
    t(F, 'shy', AWK, '잠깐… 여기 앉아도 될까요?', '잠깐… 여기 앉아도 될까?'),
    t(S, 'shy', AWK, '네, 앉으세요.', '어, 앉아.')),
  b('awkward-13', 'resting-together', AWKWARD,
    t(F, 'shy', AWK, '말이 없어도 괜찮을까요?', '말이 없어도 괜찮을까?'),
    t(S, 'calm', AWK, '네, 저도 그게 편해요.', '응, 나도 그게 편해.')),
  b('awkward-14', 'worried', AWKWARD,
    t(F, 'shy', AWK, '저… 표정이 안 좋아 보이는데, 괜찮으세요?', '저… 표정이 안 좋아 보이는데, 괜찮아?'),
    t(S, 'shy', AWK, '아, 괜찮아요. 신경 써 줘서 고마워요.', '아, 괜찮아. 신경 써 줘서 고마워.')),
  b('awkward-15', 'comfort', AWKWARD,
    t(F, 'shy', AWK, '힘든 일 있으면… 말해도 돼요.', '힘든 일 있으면… 말해도 돼.'),
    t(S, 'shy', AWK, '고마워요. 그 말만으로도 충분해요.', '고마워. 그 말만으로도 충분해.')),
  b('awkward-16', 'compliment', AWKWARD,
    t(F, 'shy', AWK, '그, 오늘 표정이 밝아 보이네요.', '그, 오늘 표정이 밝아 보이네.'),
    t(S, 'shy', AWK, '아… 그런가요. 고마워요.', '아… 그런가. 고마워.')),
  b('awkward-17', 'favor', AWKWARD,
    t(F, 'shy', AWK, '저기, 혹시… 부탁 하나 해도 될까요?', '저기, 혹시… 부탁 하나 해도 될까?'),
    t(S, 'shy', AWK, '네, 말씀해 보세요.', '어, 말해 봐.'),
    t(F, 'shy', AWK, '별건 아니고, 잠깐 시간만요.', '별건 아니고, 잠깐 시간만.')),
  b('awkward-18', 'gratitude', AWKWARD,
    t(F, 'shy', AWK, '아까는… 고마웠어요.', '아까는… 고마웠어.'),
    t(S, 'shy', AWK, '아니에요, 별거 아니었어요.', '아니야, 별거 아니었어.')),
  b('awkward-19', 'dinner', AWKWARD,
    t(F, 'shy', AWK, '저녁… 같이 드실래요?', '저녁… 같이 먹을래?'),
    t(S, 'shy', AWK, '아, 네. 좋아요.', '아, 어. 좋아.')),
  b('awkward-20', 'day-wrap-up', AWKWARD,
    t(F, 'shy', AWK, '오늘 하루… 어떠셨어요?', '오늘 하루… 어땠어?'),
    t(S, 'shy', AWK, '그냥 그랬어요. 그쪽은요?', '그냥 그랬어. 너는?'),
    t(F, 'shy', AWK, '저도 비슷했어요.', '나도 비슷했어.')),
  b('awkward-21', 'pre-bedtime', AWKWARD,
    t(F, 'shy', AWK, '이제 슬슬… 쉬어야겠어요.', '이제 슬슬… 쉬어야겠어.'),
    t(S, 'shy', AWK, '네, 오늘도 이야기 나눠서 좋았어요.', '응, 오늘도 이야기 나눠서 좋았어.')),
  b('awkward-22', 'bedtime', AWKWARD,
    t(F, 'shy', AWK, '그럼… 잘 자요.', '그럼… 잘 자.'),
    t(S, 'shy', AWK, '네, 그쪽도 잘 자요.', '응, 너도 잘 자.')),
  b('awkward-23', 'encounter', AWKWARD,
    t(F, 'shy', AWK, '어, 이쪽에 계셨네요.', '어, 이쪽에 있었네.'),
    t(S, 'shy', AWK, '아… 네. 방금 왔어요.', '아… 응. 방금 왔어.')),
  b('awkward-24', 'casual-chat', AWKWARD,
    t(F, 'shy', AWK, '이야기하는 게 처음보단 편해졌어요.', '이야기하는 게 처음보단 편해졌어.'),
    t(S, 'shy', AWK, '저도 그렇게 느껴요.', '나도 그렇게 느껴.')),
  b('awkward-25', 'casual-chat', AWKWARD,
    t(F, 'neutral', NEU, '이 방, 자주 오세요?', '이 방, 자주 와?'),
    t(S, 'shy', AWK, '가끔요. 조용해서 마음에 들어요.', '가끔. 조용해서 마음에 들어.')),
  b('awkward-26', 'compliment', AWKWARD,
    t(F, 'shy', AWK, '아까 그 말… 좋았어요.', '아까 그 말… 좋았어.'),
    t(S, 'shy', AWK, '아, 정말요? 다행이에요.', '아, 정말? 다행이야.')),
  b('awkward-27', 'teasing', AWKWARD,
    t(F, 'shy', AWK, '그, 농담 하나 해도 될까요?', '그, 농담 하나 해도 될까?'),
    t(S, 'shy', AWK, '네, 해 보세요.', '어, 해 봐.'),
    t(F, 'shy', AWK, '음… 생각해 보니 별로 안 웃기네요.', '음… 생각해 보니 별로 안 웃기네.'),
    t(S, 'shy', AWK, '그래도 시도는 좋았어요.', '그래도 시도는 좋았어.')),
  b('awkward-28', 'worried', AWKWARD,
    t(F, 'shy', AWK, '혹시 무슨 일 있으신 건 아니죠?', '혹시 무슨 일 있는 건 아니지?'),
    t(S, 'shy', AWK, '아니에요, 그냥 잠깐 그랬어요.', '아니야, 그냥 잠깐 그랬어.')),
  b('awkward-29', 'gratitude', AWKWARD,
    t(F, 'shy', AWK, '이렇게 얘기해 줘서 고마워요.', '이렇게 얘기해 줘서 고마워.'),
    t(S, 'shy', AWK, '저도… 편하게 대해 줘서 고마워요.', '나도… 편하게 대해 줘서 고마워.')),
  b('awkward-30', 'casual-chat', AWKWARD,
    t(F, 'shy', AWK, '조금씩 가까워지는 것 같아서 좋아요.', '조금씩 가까워지는 것 같아서 좋아.'),
    t(S, 'shy', AWK, '저도 그렇게 느껴요. 천천히요.', '나도 그렇게 느껴. 천천히.')),
]

export const RELATIONSHIP_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  ...NEUTRAL_DIALOGUE_BUNDLES,
  ...FRIEND_DIALOGUE_BUNDLES,
  ...CLOSE_DIALOGUE_BUNDLES,
  ...FAMILY_DIALOGUE_BUNDLES,
  ...RIVAL_DIALOGUE_BUNDLES,
  ...AWKWARD_DIALOGUE_BUNDLES,
]
