import type { DefaultDialogueBundleDef, DefaultDialogueTurn } from './defaultDialogueLibrary'
import type { RelationshipType } from './relationshipConfig'

/**
 * Affection bundles for the two romantic relationship types, kept as static
 * data (never copied into user saves) and merged into
 * `DEFAULT_DIALOGUE_BUNDLES`. Three groups, told apart by id prefix *and* by
 * `relationshipTypes` (the engine filters on the latter, the tests check the
 * two agree):
 *   - `love-XX`   70 bundles (01-40 original + 41-70 batch 2), `['romantic']`   — 연인 only
 *   - `spouse-XX` 70 bundles (01-40 original + 41-70 batch 2), `['married']`    — 부부 only
 *   - `affection-XX` 20 bundles, both          — 연인·부부 공용
 *
 * Batch 2 (love-41..70 / spouse-41..70) keeps the same authoring rules and
 * adds no new relationship id or storage shape — see romance.test.tsx for the
 * updated counts. 연인 batch 2 leans into 설렘/보고 싶은 마음/다정한 장난/칭찬 per
 * the spec; 부부 batch 2 leans into 익숙한 다정함/서로 챙기기/편안한 애정 표현/함께하는
 * 일상의 행복 — neither assumes a marriage length, children, or any other
 * unset fact (checked by the same forbidden-word test as batch 1).
 *
 * Authoring rules: every bundle is one connected 2-4 turn exchange; both the
 * 존댓말 and 반말 text of every turn is hand-written; no nicknames or terms of
 * address (여보/자기/당신 …) since the user's own 호칭 setting isn't read here;
 * no invented marriage length, children, jobs or shared history; no claim of
 * an action the simulation doesn't perform (sitting, cooking, sleeping, going
 * out) — only talk about the moment, the time of day and feelings.
 * Personality reads through each turn's `emotion`/`tags` (`lineAffinity` in
 * personalityTags.ts) and through text length (short turns suit 무뚝뚝함/과묵함).
 *
 * **Tone audit (found via user report, fixed at the root, not patched
 * around)**: `spouse-49`'s reply line used to read as a mocking retort
 * ("그렇게 잘 아는 척은 여전하네요" — "still pretending to know so well, as
 * usual") despite being tagged identically (`emotion: 'playful'`, `tags: PL`)
 * to every other warm teasing turn in this file — the engine has no way to
 * tell affectionate teasing apart from a cold one by metadata alone, only by
 * the actual words, so this had to be a content fix, not a weighting one.
 * Rewritten to land the same "우리는 서로를 잘 안다" beat without the jab. A
 * grep across every relationship-flavored dialogue file (romance +
 * relationshipDialogueLibrary.ts) for this and related dismissive/testing/
 * passive-aggressive patterns found no other occurrence — see
 * `romance.test.tsx`'s own "부부 대화는 비꼬거나 냉소적으로 들리지 않는다" describe
 * block, which turns that audit into a standing, reusable regression test
 * (scans every bundle reachable by a *warm* relationship type, not just
 * spouse-*, and separately simulates many real `married`-pair generations)
 * rather than leaving this as a one-off manual check.
 */

const LOVE: RelationshipType[] = ['romantic']
const SPOUSE: RelationshipType[] = ['married']
const BOTH: RelationshipType[] = ['romantic', 'married']

const F = 'first' as const
const S = 'second' as const

// Tag sets the personality heuristics look at (see OVERRIDES in personalityTags.ts).
const AF = ['애정', '다정']
const PL = ['장난', '애정']
const CA = ['차분', '애정']
const SH = ['수줍', '애정']
const EN = ['반가', '애정']

function t(speaker: 'first' | 'second', emotion: string, tags: string[], formal: string, casual: string): DefaultDialogueTurn {
  return { speaker, emotion, tags, text: { formal, casual } }
}

function b(id: string, categoryId: string, relationshipTypes: RelationshipType[], ...turns: DefaultDialogueTurn[]): DefaultDialogueBundleDef {
  return { id, categoryId, relationshipTypes, romantic: true, turns }
}

/** 연인 전용 (40) */
export const LOVER_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('love-01', 'encounter', LOVE,
    t(F, 'excited', EN, '어, 여기 있었네요. 보니까 반가워요.', '어, 여기 있었네. 보니까 반갑다.'),
    t(S, 'warm', AF, '저도요. 얼굴 보니까 하루가 환해지는 느낌이에요.', '나도. 얼굴 보니까 하루가 환해지는 느낌이야.')),
  b('love-02', 'encounter', LOVE,
    t(F, 'warm', AF, '잠깐 안 보였을 뿐인데 벌써 보고 싶었어요.', '잠깐 안 보였을 뿐인데 벌써 보고 싶었어.'),
    t(S, 'shy', SH, '그런 말은 갑자기 하시면 곤란해요.', '그런 말은 갑자기 하면 곤란한데.'),
    t(F, 'playful', PL, '그럼 다음엔 미리 말씀드릴게요.', '그럼 다음엔 미리 말해 줄게.')),
  b('love-03', 'encounter', LOVE,
    t(F, 'happy', EN, '여기서 만나다니, 오늘은 운이 좋네요.', '여기서 만나다니, 오늘 운 좋다.'),
    t(S, 'warm', AF, '저도 방금 같은 생각 했어요.', '나도 방금 같은 생각 했어.')),
  b('love-04', 'morning-greeting', LOVE,
    t(F, 'warm', AF, '좋은 아침이에요. 잘 잤어요?', '좋은 아침. 잘 잤어?'),
    t(S, 'happy', EN, '네, 덕분에요. 아침부터 얼굴 보니까 좋네요.', '응, 덕분에. 아침부터 얼굴 보니까 좋다.'),
    t(F, 'warm', AF, '저도요. 오늘도 좋은 하루 보내요.', '나도. 오늘도 좋은 하루 보내자.')),
  b('love-05', 'morning-greeting', LOVE,
    t(F, 'warm', AF, '오늘 하루도 응원할게요.', '오늘 하루도 응원할게.'),
    t(S, 'happy', AF, '그 말 들으니까 힘이 나요. 고마워요.', '그 말 들으니까 힘나. 고마워.')),
  b('love-06', 'wake-up', LOVE,
    t(F, 'gentle', AF, '아직 졸려 보이네요. 조금 더 쉬어도 돼요.', '아직 졸려 보이네. 조금 더 쉬어도 돼.'),
    t(S, 'sleepy', CA, '조금만 더 그럴게요. 옆에 있어 줘서 고마워요.', '조금만 더 그럴래. 옆에 있어 줘서 고마워.')),
  b('love-07', 'breakfast', LOVE,
    t(F, 'warm', AF, '아침은 챙겨 먹었어요? 같이 먹으면 좋겠어요.', '아침은 챙겨 먹었어? 같이 먹으면 좋겠다.'),
    t(S, 'happy', EN, '아직요. 그럼 같이 먹어요.', '아직. 그럼 같이 먹자.')),
  b('love-08', 'lunch', LOVE,
    t(F, 'warm', AF, '점심때네요. 밥 거르지 말아요.', '점심때네. 밥 거르지 마.'),
    t(S, 'warm', AF, '네, 걱정해 줘서 고마워요. 같이 먹을래요?', '응, 걱정해 줘서 고마워. 같이 먹을래?')),
  b('love-09', 'lunch', LOVE,
    t(F, 'playful', PL, '점심 메뉴 고르는 데 오래 걸릴 것 같은데요.', '점심 메뉴 고르는 데 오래 걸릴 것 같은데.'),
    t(S, 'warm', AF, '그럼 고민하는 동안 옆에 있어 줘요.', '그럼 고민하는 동안 옆에 있어 줘.')),
  b('love-10', 'casual-chat', LOVE,
    t(F, 'warm', AF, '가만히 보고 있으면 눈을 못 떼겠어요.', '가만히 보고 있으면 눈을 못 떼겠어.'),
    t(S, 'shy', SH, '그렇게 보면 부끄럽잖아요.', '그렇게 보면 부끄럽잖아.'),
    t(F, 'playful', PL, '부끄러워하는 것도 보기 좋은걸요.', '부끄러워하는 것도 보기 좋은걸.')),
  b('love-11', 'casual-chat', LOVE,
    t(F, 'warm', AF, '그냥 같이 있고 싶어서요. 다른 이유는 없어요.', '그냥 같이 있고 싶어서. 다른 이유는 없어.'),
    t(S, 'warm', CA, '그거면 충분해요.', '그거면 충분해.')),
  b('love-12', 'compliment', LOVE,
    t(F, 'warm', AF, '오늘 분위기가 참 좋아 보여요.', '오늘 분위기가 참 좋아 보여.'),
    t(S, 'happy', SH, '정말요? 그런 말 들으니까 기분 좋네요.', '정말? 그런 말 들으니까 기분 좋네.')),
  b('love-13', 'compliment', LOVE,
    t(F, 'warm', AF, '웃는 모습이 참 보기 좋아요.', '웃는 모습이 참 보기 좋아.'),
    t(S, 'shy', SH, '갑자기 그런 말을 들으니 쑥스러워요.', '갑자기 그런 말 들으니 쑥스럽다.'),
    t(F, 'warm', AF, '쑥스러워하는 것까지 좋아요.', '쑥스러워하는 것까지 좋아.')),
  b('love-14', 'teasing', LOVE,
    t(F, 'playful', PL, '지금 표정 너무 진지한데요. 무슨 생각 해요?', '지금 표정 너무 진지한데. 무슨 생각 해?'),
    t(S, 'neutral', CA, '별거 아니에요. 그냥 멍하니 있었어요.', '별거 아니야. 그냥 멍하니 있었어.'),
    t(F, 'playful', PL, '멍하니 있는 것도 귀여워서 봐 줄게요.', '멍하니 있는 것도 귀여워서 봐 줄게.')),
  b('love-15', 'teasing', LOVE,
    t(F, 'playful', PL, '혹시 나 보려고 일부러 온 거예요?', '혹시 나 보려고 일부러 온 거야?'),
    t(S, 'shy', SH, '들켰네요. 조금은요.', '들켰네. 조금은.')),
  b('love-16', 'worried', LOVE,
    t(F, 'worried', AF, '표정이 조금 지쳐 보여요. 괜찮아요?', '표정이 조금 지쳐 보여. 괜찮아?'),
    t(S, 'calm', CA, '조금 피곤할 뿐이에요. 걱정 안 해도 돼요.', '조금 피곤할 뿐이야. 걱정 안 해도 돼.'),
    t(F, 'warm', AF, '걱정은 제 몫이니까 쉬엄쉬엄 해요.', '걱정은 내 몫이니까 쉬엄쉬엄 해.')),
  b('love-17', 'worried', LOVE,
    t(F, 'worried', AF, '물이라도 좀 마시고 쉬어요.', '물이라도 좀 마시고 쉬어.'),
    t(S, 'warm', AF, '챙겨 줘서 고마워요. 그럴게요.', '챙겨 줘서 고마워. 그럴게.')),
  b('love-18', 'comfort', LOVE,
    t(F, 'warm', AF, '무슨 일이 있어도 저는 같은 편이에요.', '무슨 일이 있어도 난 네 편이야.'),
    t(S, 'warm', CA, '그 말 하나로 마음이 놓여요.', '그 말 하나로 마음이 놓여.')),
  b('love-19', 'comfort', LOVE,
    t(F, 'gentle', AF, '힘들면 말해요. 같이 생각해 볼게요.', '힘들면 말해. 같이 생각해 볼게.'),
    t(S, 'warm', CA, '네, 고마워요. 지금은 그 말만으로도 충분해요.', '응, 고마워. 지금은 그 말만으로도 충분해.')),
  b('love-20', 'afternoon-chat', LOVE,
    t(F, 'calm', CA, '오후라 그런지 나른하네요. 잠깐 쉬어 갈래요?', '오후라 그런지 나른하네. 잠깐 쉬어 갈래?'),
    t(S, 'happy', EN, '좋아요. 같이 쉬면 더 좋고요.', '좋아. 같이 쉬면 더 좋고.')),
  b('love-21', 'afternoon-chat', LOVE,
    t(F, 'warm', AF, '오늘 오후는 왠지 같이 보내고 싶었어요.', '오늘 오후는 왠지 같이 보내고 싶었어.'),
    t(S, 'happy', EN, '저도요. 마침 그런 생각 했어요.', '나도. 마침 그런 생각 했어.')),
  b('love-22', 'snack', LOVE,
    t(F, 'happy', EN, '간식 시간이에요. 나눠 먹을래요?', '간식 시간이야. 나눠 먹을래?'),
    t(S, 'happy', AF, '좋아요. 같이 먹으면 더 맛있어요.', '좋아. 같이 먹으면 더 맛있어.')),
  b('love-23', 'resting-together', LOVE,
    t(F, 'shy', SH, '옆에 있어도 될까요?', '옆에 있어도 될까?'),
    t(S, 'warm', AF, '물론이죠. 안 그래도 옆에 있었으면 했어요.', '물론이지. 안 그래도 옆에 있었으면 했어.')),
  b('love-24', 'resting-together', LOVE,
    t(F, 'calm', CA, '아무 말 없이 있어도 좋네요.', '아무 말 없이 있어도 좋네.'),
    t(S, 'calm', CA, '그러게요. 조용한 시간도 함께면 좋아요.', '그러게. 조용한 시간도 함께면 좋아.')),
  b('love-25', 'calling-partner', LOVE,
    t(F, 'playful', PL, '그냥 불러 봤어요. 이유는 없어요.', '그냥 불러 봤어. 이유는 없어.'),
    t(S, 'warm', AF, '이유 없이 불러 줘도 좋아요.', '이유 없이 불러 줘도 좋아.')),
  b('love-26', 'calling-partner', LOVE,
    t(F, 'curious', AF, '지금 뭐 하고 있었어요?', '지금 뭐 하고 있었어?'),
    t(S, 'happy', AF, '그냥 있었어요. 그런데 보니까 기분이 좋아졌어요.', '그냥 있었어. 근데 보니까 기분이 좋아졌어.')),
  b('love-27', 'gratitude', LOVE,
    t(F, 'warm', AF, '챙겨 줘서 고마워요. 마음이 든든해져요.', '챙겨 줘서 고마워. 마음이 든든해져.'),
    t(S, 'warm', AF, '고마워할 것 없어요. 그러고 싶어서 하는 거예요.', '고마워할 것 없어. 그러고 싶어서 하는 거야.')),
  b('love-28', 'day-wrap-up', LOVE,
    t(F, 'warm', AF, '오늘 하루도 수고했어요.', '오늘 하루도 수고했어.'),
    t(S, 'warm', AF, '고마워요. 그 말 들으니 피로가 풀리는 것 같아요.', '고마워. 그 말 들으니 피로가 풀리는 것 같아.')),
  b('love-29', 'day-wrap-up', LOVE,
    t(F, 'curious', AF, '오늘 하루는 어땠어요?', '오늘 하루는 어땠어?'),
    t(S, 'calm', CA, '무난했어요. 지금은 이렇게 함께 있어서 좋고요.', '무난했어. 지금은 이렇게 함께 있어서 좋고.'),
    t(F, 'warm', AF, '그럼 됐어요. 이제 편히 쉬어요.', '그럼 됐어. 이제 편히 쉬어.')),
  b('love-30', 'dinner', LOVE,
    t(F, 'happy', EN, '저녁은 뭘 먹을지 같이 정해 볼래요?', '저녁은 뭘 먹을지 같이 정해 볼래?'),
    t(S, 'happy', AF, '좋아요. 같이 먹는 거면 뭐든 좋아요.', '좋아. 같이 먹는 거면 뭐든 좋아.')),
  b('love-31', 'pre-bedtime', LOVE,
    t(F, 'calm', CA, '슬슬 하루를 마무리할 시간이네요.', '슬슬 하루를 마무리할 시간이네.'),
    t(S, 'shy', SH, '벌써요? 조금만 더 이야기하고 싶은데요.', '벌써? 조금만 더 이야기하고 싶은데.'),
    t(F, 'warm', AF, '그래요, 조금만 더 있어요.', '그래, 조금만 더 있자.')),
  b('love-32', 'pre-bedtime', LOVE,
    t(F, 'calm', CA, '밤이 되니까 조용해서 좋아요.', '밤이 되니까 조용해서 좋아.'),
    t(S, 'warm', CA, '이런 조용한 시간에 함께 있으니 더 좋아요.', '이런 조용한 시간에 함께 있으니 더 좋아.')),
  b('love-33', 'bedtime', LOVE,
    t(F, 'sleepy', AF, '이만 쉴게요. 오늘도 고마웠어요.', '이만 쉴게. 오늘도 고마웠어.'),
    t(S, 'warm', AF, '잘 자요. 좋은 생각만 하면서요.', '잘 자. 좋은 생각만 하면서.')),
  b('love-34', 'bedtime', LOVE,
    t(F, 'warm', AF, '내일 아침에 또 봐요.', '내일 아침에 또 보자.'),
    t(S, 'warm', AF, '네, 내일 봐요. 푹 쉬어요.', '응, 내일 보자. 푹 쉬어.')),
  b('love-35', 'casual-chat', LOVE,
    t(F, 'shy', SH, '갑자기 하고 싶은 말이 생겼어요.', '갑자기 하고 싶은 말이 생겼어.'),
    t(S, 'curious', AF, '무슨 말인데요?', '무슨 말인데?'),
    t(F, 'warm', AF, '좋아해요. 그냥 그 말이 하고 싶었어요.', '좋아해. 그냥 그 말이 하고 싶었어.'),
    t(S, 'happy', AF, '저도 좋아해요. 갑작스러워도 기뻐요.', '나도 좋아해. 갑작스러워도 기뻐.')),
  b('love-36', 'casual-chat', LOVE,
    t(F, 'warm', AF, '볼수록 더 좋아지는 것 같아요.', '볼수록 더 좋아지는 것 같아.'),
    t(S, 'shy', SH, '저도 그래요. 이상하죠, 볼수록 더 좋아요.', '나도 그래. 이상하지, 볼수록 더 좋아.')),
  b('love-37', 'casual-chat', LOVE,
    t(F, 'happy', EN, '같이 있으면 시간이 참 빨리 가요.', '같이 있으면 시간이 참 빨리 가.'),
    t(S, 'warm', AF, '그러게요. 더 천천히 갔으면 좋겠어요.', '그러게. 더 천천히 갔으면 좋겠어.')),
  b('love-38', 'encounter', LOVE,
    t(F, 'shy', SH, '마주칠 때마다 조금 설레요.', '마주칠 때마다 조금 설레.'),
    t(S, 'happy', AF, '저도요. 살짝 두근거려요.', '나도. 살짝 두근거려.')),
  b('love-39', 'comfort', LOVE,
    t(F, 'gentle', AF, '혼자 끙끙대지 말아요. 곁에 있을게요.', '혼자 끙끙대지 마. 곁에 있을게.'),
    t(S, 'warm', CA, '네, 그렇게 말해 주니 마음이 편해져요.', '응, 그렇게 말해 주니 마음이 편해져.')),
  b('love-40', 'gratitude', LOVE,
    t(F, 'warm', AF, '곁에 있어 줘서 고마워요.', '곁에 있어 줘서 고마워.'),
    t(S, 'warm', AF, '저야말로요. 함께라서 든든해요.', '나야말로. 함께라서 든든해.')),

  // ---- 배치 2 (41-70): 설렘 / 보고 싶은 마음 / 다정한 장난 / 칭찬 / 애정 표현 ----
  b('love-41', 'encounter', LOVE,
    t(F, 'excited', EN, '복도에서부터 심장이 콩닥거렸어요.', '복도에서부터 심장이 콩닥거렸어.'),
    t(S, 'curious', CA, '왜 그렇게 뛰어와요? 넘어지겠어요.', '왜 그렇게 뛰어와? 넘어지겠어.'),
    t(F, 'shy', SH, '보고 싶은 마음이 발보다 빨라서 그래요.', '보고 싶은 마음이 발보다 빨라서 그래.')),
  b('love-42', 'encounter', LOVE,
    t(F, 'happy', EN, '이 방에 있을 것 같더라니, 역시네요.', '이 방에 있을 것 같더라니, 역시네.'),
    t(S, 'curious', CA, '제가 여기 있는 거 어떻게 알았어요?', '내가 여기 있는 거 어떻게 알았어?'),
    t(F, 'warm', AF, '그냥 느낌으로요. 자주 생각하다 보니까요.', '그냥 느낌으로. 자주 생각하다 보니까.')),
  b('love-43', 'casual-chat', LOVE,
    t(F, 'shy', SH, '아까부터 자꾸 눈으로 찾고 있었어요.', '아까부터 자꾸 눈으로 찾고 있었어.'),
    t(S, 'curious', CA, '저를요? 왜 그랬어요?', '나를? 왜 그랬어?'),
    t(F, 'warm', AF, '그냥 얼굴이 보고 싶어서요.', '그냥 얼굴이 보고 싶어서.')),
  b('love-44', 'casual-chat', LOVE,
    t(F, 'shy', SH, '잠깐 안 보이면 괜히 두리번거리게 돼요.', '잠깐 안 보이면 괜히 두리번거리게 돼.'),
    t(S, 'playful', PL, '그 정도예요? 귀엽네요.', '그 정도야? 귀엽다.')),
  b('love-45', 'compliment', LOVE,
    t(F, 'warm', AF, '지금 그 표정, 진짜 예뻐요.', '지금 그 표정, 진짜 예뻐.'),
    t(S, 'shy', SH, '갑자기 그런 말 하면 반칙이에요.', '갑자기 그런 말 하면 반칙이야.'),
    t(F, 'playful', PL, '반칙이어도 사실이라 어쩔 수 없어요.', '반칙이어도 사실이라 어쩔 수 없어.')),
  b('love-46', 'compliment', LOVE,
    t(F, 'warm', AF, '그렇게 웃을 때마다 넋을 놓게 돼요.', '그렇게 웃을 때마다 넋을 놓게 돼.'),
    t(S, 'shy', SH, '그 정도는 아닐 텐데요.', '그 정도는 아닐 텐데.'),
    t(F, 'warm', AF, '제 눈에는 그 정도예요.', '내 눈엔 그 정도야.')),
  b('love-47', 'compliment', LOVE,
    t(F, 'warm', AF, '말하는 목소리 톤이 참 좋아요.', '말하는 목소리 톤이 참 좋아.'),
    t(S, 'shy', SH, '그런 것까지 눈여겨봤어요?', '그런 것까지 눈여겨봤어?'),
    t(F, 'playful', PL, '당연하죠, 다 좋아 보이는걸요.', '당연하지, 다 좋아 보이는걸.')),
  b('love-48', 'compliment', LOVE,
    t(F, 'warm', AF, '오늘 입은 옷, 잘 어울려요.', '오늘 입은 옷, 잘 어울려.'),
    t(S, 'happy', SH, '고마워요, 신경 좀 썼어요.', '고마워, 신경 좀 썼어.')),
  b('love-49', 'teasing', LOVE,
    t(F, 'playful', PL, '지금 얼굴 빨개진 거 다 보여요.', '지금 얼굴 빨개진 거 다 보여.'),
    t(S, 'shy', SH, '아니에요, 더워서 그래요.', '아니야, 더워서 그래.'),
    t(F, 'playful', PL, '핑계가 점점 늘어나네요.', '핑계가 점점 늘어나네.')),
  b('love-50', 'teasing', LOVE,
    t(F, 'playful', PL, '방금 저 보고 웃었죠? 다 봤어요.', '방금 나 보고 웃었지? 다 봤어.'),
    t(S, 'neutral', CA, '아무것도 안 웃었는데요.', '아무것도 안 웃었는데.'),
    t(F, 'playful', PL, '표정이 이미 웃고 있는데요.', '표정이 이미 웃고 있는데.')),
  b('love-51', 'teasing', LOVE,
    t(F, 'playful', PL, '자꾸 곁눈질하는 거 티 나요.', '자꾸 곁눈질하는 거 티 나.'),
    t(S, 'shy', SH, '티 나면 어때요, 보고 싶은데요.', '티 나면 어때, 보고 싶은데.')),
  b('love-52', 'teasing', LOVE,
    t(F, 'playful', PL, '오늘따라 왜 이렇게 제 옆만 맴돌아요?', '오늘따라 왜 이렇게 내 옆만 맴돌아?'),
    t(S, 'shy', SH, '그냥요, 옆이 편해서요.', '그냥, 옆이 편해서.'),
    t(F, 'warm', AF, '그 대답, 마음에 들어요.', '그 대답, 마음에 들어.')),
  b('love-53', 'worried', LOVE,
    t(F, 'worried', AF, '표정이 살짝 굳어 있어요. 무슨 일 있어요?', '표정이 살짝 굳어 있어. 무슨 일 있어?'),
    t(S, 'neutral', CA, '아니에요, 그냥 딴생각 좀 했어요.', '아니야, 그냥 딴생각 좀 했어.'),
    t(F, 'gentle', AF, '저한테는 말해도 돼요. 기다릴게요.', '나한테는 말해도 돼. 기다릴게.')),
  b('love-54', 'comfort', LOVE,
    t(F, 'gentle', AF, '복잡한 생각은 잠깐 내려놔요.', '복잡한 생각은 잠깐 내려놔.'),
    t(S, 'warm', CA, '그 말 들으니까 마음이 스르르 풀려요.', '그 말 들으니까 마음이 스르르 풀려.')),
  b('love-55', 'resting-together', LOVE,
    t(F, 'warm', AF, '이렇게 붙어 있으니까 시간이 안 가면 좋겠어요.', '이렇게 붙어 있으니까 시간이 안 가면 좋겠어.'),
    t(S, 'happy', AF, '저도 그 생각 하고 있었어요.', '나도 그 생각 하고 있었어.')),
  b('love-56', 'resting-together', LOVE,
    t(F, 'calm', CA, '머리가 복잡할 땐 이렇게 있는 게 최고예요.', '머리가 복잡할 땐 이렇게 있는 게 최고야.'),
    t(S, 'calm', CA, '동의해요. 아무 말 안 해도 좋아요.', '동의해. 아무 말 안 해도 좋아.')),
  b('love-57', 'calling-partner', LOVE,
    t(F, 'playful', PL, '저기요, 잠깐 이리 와 볼래요?', '저기, 잠깐 이리 와 볼래?'),
    t(S, 'curious', CA, '왜요, 무슨 일이에요?', '왜, 무슨 일이야?'),
    t(F, 'shy', SH, '그냥 가까이서 보고 싶어서요.', '그냥 가까이서 보고 싶어서.')),
  b('love-58', 'calling-partner', LOVE,
    t(F, 'happy', AF, '이름 부르는 것만으로 기분이 좋아져요.', '이름 부르는 것만으로 기분이 좋아져.'),
    t(S, 'warm', AF, '그럼 자주 불러 줘요.', '그럼 자주 불러 줘.')),
  b('love-59', 'gratitude', LOVE,
    t(F, 'warm', AF, '옆에 있어 준 것만으로도 오늘 하루가 달랐어요.', '옆에 있어 준 것만으로도 오늘 하루가 달랐어.'),
    t(S, 'happy', AF, '그 말 들으니 저도 기뻐요.', '그 말 들으니 나도 기뻐.')),
  b('love-60', 'day-wrap-up', LOVE,
    t(F, 'curious', AF, '오늘 있었던 일 중에 제일 좋았던 순간이 언제였어요?', '오늘 있었던 일 중에 제일 좋았던 순간이 언제였어?'),
    t(S, 'shy', SH, '지금 이 순간이요.', '지금 이 순간.'),
    t(F, 'warm', AF, '저도 같은 답이었어요.', '나도 같은 답이었어.')),
  b('love-61', 'dinner', LOVE,
    t(F, 'happy', AF, '저녁 먹으면서 오늘 얘기 들려줘요.', '저녁 먹으면서 오늘 얘기 들려줘.'),
    t(S, 'happy', EN, '좋아요. 듣다 보면 하루가 다 재밌어질 것 같아요.', '좋아. 듣다 보면 하루가 다 재밌어질 것 같아.')),
  b('love-62', 'pre-bedtime', LOVE,
    t(F, 'shy', SH, '오늘 밤은 유독 헤어지기가 아쉽네요.', '오늘 밤은 유독 헤어지기가 아쉽네.'),
    t(S, 'warm', AF, '그럼 조금만 더 붙어 있어요.', '그럼 조금만 더 붙어 있자.')),
  b('love-63', 'bedtime', LOVE,
    t(F, 'warm', AF, '눈 감기 전에 마지막으로 얼굴 한 번 더 봐요.', '눈 감기 전에 마지막으로 얼굴 한 번 더 보자.'),
    t(S, 'happy', AF, '좋아요. 이 얼굴 기억하면서 잘게요.', '좋아. 이 얼굴 기억하면서 잘게.')),
  b('love-64', 'bedtime', LOVE,
    t(F, 'shy', SH, '오늘 밤 꿈에는 제가 나왔으면 좋겠어요.', '오늘 밤 꿈에는 내가 나왔으면 좋겠어.'),
    t(S, 'playful', PL, '이미 나올 것 같은 예감이 들어요.', '이미 나올 것 같은 예감이 들어.')),
  b('love-65', 'favor', LOVE,
    t(F, 'shy', SH, '부탁 하나만 해도 될까요? 어렵지 않은 거예요.', '부탁 하나만 해도 될까? 어렵지 않은 거야.'),
    t(S, 'curious', CA, '뭔데요, 말해 봐요.', '뭔데, 말해 봐.'),
    t(F, 'shy', SH, '그냥 잠깐 손 좀 잡아 줘요.', '그냥 잠깐 손 좀 잡아 줘.')),
  b('love-66', 'apology', LOVE,
    t(F, 'apologetic', AF, '아까 조금 무뚝뚝했죠. 미안해요.', '아까 조금 무뚝뚝했지. 미안해.'),
    t(S, 'calm', CA, '괜찮아요, 그런 날도 있는 거죠.', '괜찮아, 그런 날도 있는 거지.'),
    t(F, 'warm', AF, '이해해 줘서 오히려 제가 고마워요.', '이해해 줘서 오히려 내가 고마워.')),
  b('love-67', 'afternoon-chat', LOVE,
    t(F, 'warm', AF, '오후 햇살 받는 얼굴이 오늘따라 눈부셔요.', '오후 햇살 받는 얼굴이 오늘따라 눈부셔.'),
    t(S, 'shy', SH, '괜히 그런 말 하면 쳐다보기 민망해져요.', '괜히 그런 말 하면 쳐다보기 민망해져.')),
  b('love-68', 'snack', LOVE,
    t(F, 'happy', AF, '이거 한입만 먹어 볼래요? 나눠 먹고 싶어서요.', '이거 한입만 먹어 볼래? 나눠 먹고 싶어서.'),
    t(S, 'happy', AF, '좋아요, 나눠 먹으니까 더 맛있는 것 같아요.', '좋아, 나눠 먹으니까 더 맛있는 것 같아.')),
  b('love-69', 'casual-chat', LOVE,
    t(F, 'happy', AF, '이유는 모르겠는데 자꾸 웃음이 나요.', '이유는 모르겠는데 자꾸 웃음이 나.'),
    t(S, 'curious', CA, '저 때문이에요?', '나 때문이야?'),
    t(F, 'warm', AF, '네, 딱 그거예요.', '응, 딱 그거야.')),
  b('love-70', 'encounter', LOVE,
    t(F, 'happy', EN, '발소리만 듣고도 알아챘어요.', '발소리만 듣고도 알아챘어.'),
    t(S, 'curious', CA, '그렇게 티가 나요?', '그렇게 티가 나?'),
    t(F, 'warm', AF, '네, 그만큼 신경 쓰고 있다는 뜻이겠죠.', '응, 그만큼 신경 쓰고 있다는 뜻이겠지.')),
]

/** 부부 전용 (40) */
export const SPOUSE_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('spouse-01', 'morning-greeting', SPOUSE,
    t(F, 'warm', AF, '잘 잤어요? 얼굴이 편안해 보이네요.', '잘 잤어? 얼굴이 편안해 보이네.'),
    t(S, 'calm', CA, '네, 푹 잤어요. 아침부터 얼굴 보니까 마음이 놓여요.', '응, 푹 잤어. 아침부터 얼굴 보니까 마음이 놓여.')),
  b('spouse-02', 'morning-greeting', SPOUSE,
    t(F, 'calm', CA, '오늘도 무리하지 말고 천천히 해요.', '오늘도 무리하지 말고 천천히 해.'),
    t(S, 'warm', AF, '그래요. 이런 말이 아침 인사 같아서 좋네요.', '그래. 이런 말이 아침 인사 같아서 좋네.')),
  b('spouse-03', 'wake-up', SPOUSE,
    t(F, 'gentle', AF, '조금 더 쉬어도 돼요. 서두를 일은 없어요.', '조금 더 쉬어도 돼. 서두를 일은 없어.'),
    t(S, 'sleepy', CA, '그럼 조금만 더요. 옆에 있으니까 마음이 편해요.', '응, 조금만 더. 옆에 있으니까 마음이 편해.')),
  b('spouse-04', 'breakfast', SPOUSE,
    t(F, 'warm', AF, '아침은 먹었어요? 안 먹었으면 같이 먹어요.', '아침은 먹었어? 안 먹었으면 같이 먹자.'),
    t(S, 'calm', CA, '아직요. 같이 먹으면 되죠.', '아직. 같이 먹으면 되지.')),
  b('spouse-05', 'lunch', SPOUSE,
    t(F, 'warm', AF, '점심때가 됐네요. 밥 챙겨 먹었어요?', '점심때가 됐네. 밥 챙겨 먹었어?'),
    t(S, 'calm', CA, '이제 먹으려고요. 같이 먹을래요?', '이제 먹으려고. 같이 먹을래?'),
    t(F, 'happy', AF, '좋아요. 그게 제일 편해요.', '좋아. 그게 제일 편해.')),
  b('spouse-06', 'lunch', SPOUSE,
    t(F, 'playful', PL, '점심 메뉴 정하는 건 언제나 어려워요.', '점심 메뉴 정하는 건 언제나 어려워.'),
    t(S, 'warm', CA, '그래도 같이 고민하는 시간이 나쁘지 않아요.', '그래도 같이 고민하는 시간이 나쁘지 않아.')),
  b('spouse-07', 'casual-chat', SPOUSE,
    t(F, 'calm', CA, '그냥 옆에 있는 것만으로도 편안해요.', '그냥 옆에 있는 것만으로도 편안해.'),
    t(S, 'warm', CA, '저도요. 말하지 않아도 편한 사이라 다행이에요.', '나도. 말하지 않아도 편한 사이라 다행이야.')),
  b('spouse-08', 'casual-chat', SPOUSE,
    t(F, 'playful', PL, '지금 무슨 생각 하는지 알 것 같아요.', '지금 무슨 생각 하는지 알 것 같아.'),
    t(S, 'playful', PL, '그래요? 그럼 맞혀 봐요.', '그래? 그럼 맞혀 봐.'),
    t(F, 'playful', PL, '글쎄요, 비밀로 해 둘게요.', '글쎄, 비밀로 해 둘게.')),
  b('spouse-09', 'compliment', SPOUSE,
    t(F, 'warm', AF, '오늘 표정이 참 좋아 보여요.', '오늘 표정이 참 좋아 보여.'),
    t(S, 'happy', CA, '그래요? 그렇게 봐 주니 고마워요.', '그래? 그렇게 봐 주니 고마워.')),
  b('spouse-10', 'compliment', SPOUSE,
    t(F, 'warm', AF, '별것 아닌 일도 차분히 해내는 모습이 좋아요.', '별것 아닌 일도 차분히 해내는 모습이 좋아.'),
    t(S, 'shy', SH, '그런 것까지 봐 주고 있었네요. 고마워요.', '그런 것까지 봐 주고 있었구나. 고마워.')),
  b('spouse-11', 'gratitude', SPOUSE,
    t(F, 'warm', AF, '챙겨 줘서 고마워요.', '챙겨 줘서 고마워.'),
    t(S, 'calm', CA, '고마울 것 없어요. 서로 그런 사이잖아요.', '고마울 것 없어. 서로 그런 사이잖아.')),
  b('spouse-12', 'gratitude', SPOUSE,
    t(F, 'warm', AF, '덕분에 마음이 편해요.', '덕분에 마음이 편해.'),
    t(S, 'warm', AF, '그렇게 말해 주니 오히려 제가 고마워요.', '그렇게 말해 주니 오히려 내가 고마워.')),
  b('spouse-13', 'teasing', SPOUSE,
    t(F, 'playful', PL, '그 표정, 뭔가 생각 중인 표정이죠.', '그 표정, 뭔가 생각 중인 표정이지.'),
    t(S, 'neutral', CA, '들켰네요. 아무것도 아닌 생각이에요.', '들켰네. 아무것도 아닌 생각이야.'),
    t(F, 'playful', PL, '아무것도 아닌 생각이 제일 궁금한데요.', '아무것도 아닌 생각이 제일 궁금한데.')),
  b('spouse-14', 'teasing', SPOUSE,
    t(F, 'playful', PL, '조금만 방심하면 금방 딴청이네요.', '조금만 방심하면 금방 딴청이네.'),
    t(S, 'playful', PL, '딴청이라니요. 잠깐 쉬고 있었을 뿐이에요.', '딴청이라니. 잠깐 쉬고 있었을 뿐이야.')),
  b('spouse-15', 'worried', SPOUSE,
    t(F, 'worried', AF, '조금 피곤해 보여요. 무리한 건 아니죠?', '조금 피곤해 보여. 무리한 건 아니지?'),
    t(S, 'calm', CA, '조금요. 그래도 괜찮아요.', '조금. 그래도 괜찮아.'),
    t(F, 'gentle', AF, '괜찮다는 말 믿을게요. 그래도 쉬어요.', '괜찮다는 말 믿을게. 그래도 쉬어.')),
  b('spouse-16', 'worried', SPOUSE,
    t(F, 'worried', AF, '목마르지 않아요? 물이라도 마셔요.', '목마르지 않아? 물이라도 마셔.'),
    t(S, 'warm', AF, '그럴게요. 이런 것까지 챙겨 줘서 고마워요.', '그럴게. 이런 것까지 챙겨 줘서 고마워.')),
  b('spouse-17', 'comfort', SPOUSE,
    t(F, 'gentle', AF, '힘든 일 있으면 나한테 기대요.', '힘든 일 있으면 나한테 기대.'),
    t(S, 'warm', CA, '네, 기댈 사람이 있어서 든든해요.', '응, 기댈 사람이 있어서 든든해.')),
  b('spouse-18', 'comfort', SPOUSE,
    t(F, 'gentle', AF, '괜찮아요. 같이 있잖아요.', '괜찮아. 같이 있잖아.'),
    t(S, 'warm', CA, '맞아요. 그 말이 제일 큰 위로예요.', '맞아. 그 말이 제일 큰 위로야.')),
  b('spouse-19', 'afternoon-chat', SPOUSE,
    t(F, 'calm', CA, '오후에는 잠깐 쉬어 가는 게 좋아요.', '오후에는 잠깐 쉬어 가는 게 좋아.'),
    t(S, 'calm', CA, '좋아요. 같이 쉬어요.', '좋아. 같이 쉬자.')),
  b('spouse-20', 'afternoon-chat', SPOUSE,
    t(F, 'warm', AF, '따뜻한 거 마시면서 쉴래요?', '따뜻한 거 마시면서 쉴래?'),
    t(S, 'happy', AF, '좋죠. 그런 시간이 참 좋아요.', '좋지. 그런 시간이 참 좋아.')),
  b('spouse-21', 'snack', SPOUSE,
    t(F, 'happy', AF, '출출한데 같이 나눠 먹어요.', '출출한데 같이 나눠 먹자.'),
    t(S, 'happy', CA, '좋아요. 나눠 먹으면 딱 좋겠어요.', '좋아. 나눠 먹으면 딱 좋겠다.')),
  b('spouse-22', 'resting-together', SPOUSE,
    t(F, 'calm', CA, '우리 잠깐 아무것도 하지 말고 쉬어요.', '우리 잠깐 아무것도 하지 말고 쉬자.'),
    t(S, 'warm', CA, '네, 그게 오늘 제일 좋은 계획이에요.', '응, 그게 오늘 제일 좋은 계획이야.')),
  b('spouse-23', 'resting-together', SPOUSE,
    t(F, 'calm', CA, '말 없이 있어도 이렇게 편안하네요.', '말 없이 있어도 이렇게 편안하네.'),
    t(S, 'calm', CA, '이런 조용함이 좋아요.', '이런 조용함이 좋아.')),
  b('spouse-24', 'encounter', SPOUSE,
    t(F, 'warm', AF, '어, 여기 있었네요. 얼굴 보니 마음이 놓여요.', '어, 여기 있었네. 얼굴 보니 마음이 놓여.'),
    t(S, 'warm', CA, '저도요. 눈에 보이면 안심이 돼요.', '나도. 눈에 보이면 안심이 돼.')),
  b('spouse-25', 'encounter', SPOUSE,
    t(F, 'happy', EN, '지나가다 보니 반갑네요.', '지나가다 보니 반갑네.'),
    t(S, 'happy', AF, '저도요. 이런 마주침도 좋아요.', '나도. 이런 마주침도 좋아.')),
  b('spouse-26', 'calling-partner', SPOUSE,
    t(F, 'playful', PL, '별일은 아닌데, 그냥 불러 봤어요.', '별일은 아닌데, 그냥 불러 봤어.'),
    t(S, 'warm', AF, '그냥 불러도 괜찮아요. 언제든지요.', '그냥 불러도 괜찮아. 언제든지.')),
  b('spouse-27', 'day-wrap-up', SPOUSE,
    t(F, 'warm', AF, '오늘도 수고 많았어요.', '오늘도 수고 많았어.'),
    t(S, 'warm', AF, '수고는요. 이렇게 말해 주는 사람이 있어서 힘이 나요.', '수고는 뭘. 이렇게 말해 주는 사람이 있어서 힘이 나.')),
  b('spouse-28', 'day-wrap-up', SPOUSE,
    t(F, 'curious', AF, '하루 어땠어요? 들려줄 얘기 있어요?', '하루 어땠어? 들려줄 얘기 있어?'),
    t(S, 'calm', CA, '특별한 건 없었어요. 그래도 이렇게 얘기하니 좋아요.', '특별한 건 없었어. 그래도 이렇게 얘기하니 좋아.'),
    t(F, 'warm', CA, '특별하지 않은 하루가 제일 좋은 거죠.', '특별하지 않은 하루가 제일 좋은 거지.')),
  b('spouse-29', 'dinner', SPOUSE,
    t(F, 'happy', AF, '저녁은 뭐 먹을지 같이 정해요.', '저녁은 뭐 먹을지 같이 정하자.'),
    t(S, 'warm', CA, '가볍게 먹어도 좋고요. 같이라서 다 좋아요.', '가볍게 먹어도 좋고. 같이라서 다 좋아.')),
  b('spouse-30', 'dinner', SPOUSE,
    t(F, 'calm', CA, '오늘 저녁은 편하게 먹어요.', '오늘 저녁은 편하게 먹자.'),
    t(S, 'calm', CA, '좋아요. 편하게, 천천히요.', '좋아. 편하게, 천천히.')),
  b('spouse-31', 'pre-bedtime', SPOUSE,
    t(F, 'calm', CA, '슬슬 쉴 준비를 해야겠네요.', '슬슬 쉴 준비를 해야겠네.'),
    t(S, 'calm', CA, '그래요. 오늘도 무사히 지나갔네요.', '그래. 오늘도 무사히 지나갔네.')),
  b('spouse-32', 'pre-bedtime', SPOUSE,
    t(F, 'calm', CA, '밤이라 그런지 집이 조용해요.', '밤이라 그런지 집이 조용해.'),
    t(S, 'warm', CA, '이런 고요함이 좋아요. 함께라서 더요.', '이런 고요함이 좋아. 함께라서 더.')),
  b('spouse-33', 'bedtime', SPOUSE,
    t(F, 'sleepy', AF, '먼저 쉴게요. 오늘도 고마웠어요.', '먼저 쉴게. 오늘도 고마웠어.'),
    t(S, 'warm', AF, '네, 잘 자요. 좋은 꿈 꿔요.', '응, 잘 자. 좋은 꿈 꿔.')),
  b('spouse-34', 'bedtime', SPOUSE,
    t(F, 'calm', CA, '내일도 잘 지내 봐요.', '내일도 잘 지내 보자.'),
    t(S, 'calm', AF, '그래요. 편히 쉬어요.', '그래. 편히 쉬어.')),
  b('spouse-35', 'bedtime', SPOUSE,
    t(F, 'sleepy', AF, '자기 전에 잠깐만 얘기해요.', '자기 전에 잠깐만 얘기하자.'),
    t(S, 'warm', CA, '좋아요. 그런 시간이 하루의 마무리 같아요.', '좋아. 그런 시간이 하루의 마무리 같아.')),
  b('spouse-36', 'casual-chat', SPOUSE,
    t(F, 'calm', CA, '이렇게 함께 있는 게 자연스럽게 느껴져요.', '이렇게 함께 있는 게 자연스럽게 느껴져.'),
    t(S, 'warm', AF, '그러게요. 당연한 것 같으면서도 고마운 일이에요.', '그러게. 당연한 것 같으면서도 고마운 일이야.')),
  b('spouse-37', 'casual-chat', SPOUSE,
    t(F, 'warm', AF, '옆에 있으면 하루가 편안해져요.', '옆에 있으면 하루가 편안해져.'),
    t(S, 'warm', CA, '저도요. 곁에 있어 주는 게 참 든든해요.', '나도. 곁에 있어 주는 게 참 든든해.')),
  b('spouse-38', 'compliment', SPOUSE,
    t(F, 'warm', AF, '웃는 얼굴을 보면 걱정이 사라져요.', '웃는 얼굴을 보면 걱정이 사라져.'),
    t(S, 'playful', PL, '그럼 자주 웃어야겠네요.', '그럼 자주 웃어야겠네.')),
  b('spouse-39', 'encounter', SPOUSE,
    t(F, 'calm', CA, '오늘도 이렇게 얼굴을 보네요.', '오늘도 이렇게 얼굴을 보네.'),
    t(S, 'warm', AF, '그러게요. 이런 평범한 순간이 좋아요.', '그러게. 이런 평범한 순간이 좋아.')),
  b('spouse-40', 'casual-chat', SPOUSE,
    t(F, 'calm', CA, '이 시간이 참 좋네요.', '이 시간이 참 좋네.'),
    t(S, 'warm', CA, '저도요. 아무 일 없이 함께인 시간이요.', '나도. 아무 일 없이 함께인 시간.')),

  // ---- 배치 2 (41-70): 익숙한 다정함 / 서로 챙기기 / 편안한 애정 표현 / 함께하는 일상의 행복 ----
  b('spouse-41', 'morning-greeting', SPOUSE,
    t(F, 'warm', AF, '눈 뜨자마자 보이는 얼굴이 여전히 좋네요.', '눈 뜨자마자 보이는 얼굴이 여전히 좋네.'),
    t(S, 'happy', AF, '그 말, 아침마다 들어도 안 질려요.', '그 말, 아침마다 들어도 안 질려.')),
  b('spouse-42', 'morning-greeting', SPOUSE,
    t(F, 'warm', AF, '오늘 컨디션은 좀 어때요?', '오늘 컨디션은 좀 어때?'),
    t(S, 'calm', CA, '나쁘지 않아요. 물어봐 줘서 고마워요.', '나쁘지 않아. 물어봐 줘서 고마워.')),
  b('spouse-43', 'breakfast', SPOUSE,
    t(F, 'gentle', AF, '입맛 없으면 가볍게라도 좀 먹어요.', '입맛 없으면 가볍게라도 좀 먹어.'),
    t(S, 'warm', CA, '그럴게요. 챙겨 주는 사람이 있어서 다행이에요.', '그럴게. 챙겨 주는 사람이 있어서 다행이야.')),
  b('spouse-44', 'lunch', SPOUSE,
    t(F, 'gentle', AF, '점심시간 놓치지 말고 꼭 챙겨 먹어요.', '점심시간 놓치지 말고 꼭 챙겨 먹어.'),
    t(S, 'happy', CA, '네, 그럴게요. 그런 잔소리도 듣기 좋아요.', '응, 그럴게. 그런 잔소리도 듣기 좋아.')),
  b('spouse-45', 'casual-chat', SPOUSE,
    t(F, 'calm', CA, '특별한 말 없이 그냥 옆에 있고 싶은 날이에요.', '특별한 말 없이 그냥 옆에 있고 싶은 날이야.'),
    t(S, 'warm', CA, '그런 날, 저도 좋아해요.', '그런 날, 나도 좋아해.')),
  b('spouse-46', 'casual-chat', SPOUSE,
    t(F, 'calm', CA, '말투만 들어도 오늘 기분이 어떤지 알겠어요.', '말투만 들어도 오늘 기분이 어떤지 알겠어.'),
    t(S, 'happy', CA, '그렇게 잘 알아채는 거, 신기하면서도 좋아요.', '그렇게 잘 알아채는 거, 신기하면서도 좋아.')),
  b('spouse-47', 'compliment', SPOUSE,
    t(F, 'warm', AF, '여전히 웃는 얼굴이 제일 좋아요.', '여전히 웃는 얼굴이 제일 좋아.'),
    t(S, 'happy', CA, '여전히라는 말이 듣기 좋네요.', '여전히라는 말이 듣기 좋네.')),
  b('spouse-48', 'compliment', SPOUSE,
    t(F, 'warm', AF, '오늘따라 편안해 보여서 저도 마음이 놓여요.', '오늘따라 편안해 보여서 나도 마음이 놓여.'),
    t(S, 'happy', CA, '그렇게 봐 주니까 진짜 편안해지는 것 같아요.', '그렇게 봐 주니까 진짜 편안해지는 것 같아.')),
  b('spouse-49', 'teasing', SPOUSE,
    t(F, 'playful', PL, '또 그 표정이네요. 저는 다 알아요.', '또 그 표정이네. 나는 다 알아.'),
    t(S, 'happy', CA, '그렇게 잘 알아봐 주는 게 좋아요.', '그렇게 잘 알아봐 주는 게 좋아.'),
    t(F, 'warm', CA, '오래 봐 온 보람이 있네요.', '오래 봐 온 보람이 있네.')),
  b('spouse-50', 'teasing', SPOUSE,
    t(F, 'playful', PL, '가끔 보면 저보다 저를 더 잘 아는 것 같아요.', '가끔 보면 나보다 나를 더 잘 아는 것 같아.'),
    t(S, 'warm', CA, '그만큼 잘 보고 있다는 뜻이겠죠.', '그만큼 잘 보고 있다는 뜻이겠지.')),
  b('spouse-51', 'worried', SPOUSE,
    t(F, 'worried', AF, '안색이 오늘 좀 안 좋아 보여요. 괜찮은 거죠?', '안색이 오늘 좀 안 좋아 보여. 괜찮은 거지?'),
    t(S, 'calm', CA, '괜찮아요. 그렇게 봐 줘서 고마워요.', '괜찮아. 그렇게 봐 줘서 고마워.'),
    t(F, 'gentle', AF, '혹시라도 힘들면 꼭 말해요.', '혹시라도 힘들면 꼭 말해.')),
  b('spouse-52', 'comfort', SPOUSE,
    t(F, 'gentle', AF, '힘든 일은 저한테 나눠 줘요. 같이 들면 가벼워져요.', '힘든 일은 나한테 나눠 줘. 같이 들면 가벼워져.'),
    t(S, 'warm', CA, '그 말이 오늘 제일 큰 힘이 되네요.', '그 말이 오늘 제일 큰 힘이 되네.')),
  b('spouse-53', 'resting-together', SPOUSE,
    t(F, 'calm', CA, '이렇게 나란히 앉아 있는 게 제일 좋은 시간이에요.', '이렇게 나란히 앉아 있는 게 제일 좋은 시간이야.'),
    t(S, 'warm', CA, '저도요. 별다른 걸 안 해도 충분해요.', '나도. 별다른 걸 안 해도 충분해.')),
  b('spouse-54', 'resting-together', SPOUSE,
    t(F, 'calm', CA, '아무 말 안 해도 편한 사이라 참 다행이에요.', '아무 말 안 해도 편한 사이라 참 다행이야.'),
    t(S, 'calm', CA, '그러게요. 이런 편안함이 좋아요.', '그러게. 이런 편안함이 좋아.')),
  b('spouse-55', 'calling-partner', SPOUSE,
    t(F, 'playful', PL, '잠깐 이름 불러 봤어요. 그냥요.', '잠깐 이름 불러 봤어. 그냥.'),
    t(S, 'warm', CA, '그냥 부르는 것도 좋네요.', '그냥 부르는 것도 좋네.')),
  b('spouse-56', 'calling-partner', SPOUSE,
    t(F, 'playful', PL, '잠깐 이쪽 좀 봐 줄래요?', '잠깐 이쪽 좀 봐 줄래?'),
    t(S, 'curious', CA, '왜요, 무슨 할 말 있어요?', '왜, 무슨 할 말 있어?'),
    t(F, 'warm', AF, '그냥 얼굴 한번 보고 싶어서요.', '그냥 얼굴 한번 보고 싶어서.')),
  b('spouse-57', 'gratitude', SPOUSE,
    t(F, 'warm', AF, '매번 챙겨 줘서 새삼 고마워요.', '매번 챙겨 줘서 새삼 고마워.'),
    t(S, 'happy', CA, '그런 말 안 해도 되는데, 그래도 들으니 좋네요.', '그런 말 안 해도 되는데, 그래도 들으니 좋네.')),
  b('spouse-58', 'gratitude', SPOUSE,
    t(F, 'warm', AF, '곁에 있어 주는 게 얼마나 큰 힘인지 몰라요.', '곁에 있어 주는 게 얼마나 큰 힘인지 몰라.'),
    t(S, 'warm', AF, '저도 똑같은 마음이에요.', '나도 똑같은 마음이야.')),
  b('spouse-59', 'day-wrap-up', SPOUSE,
    t(F, 'calm', CA, '오늘 하루도 별일 없이 지나가서 다행이에요.', '오늘 하루도 별일 없이 지나가서 다행이야.'),
    t(S, 'warm', CA, '이런 평범한 하루가 참 소중해요.', '이런 평범한 하루가 참 소중해.')),
  b('spouse-60', 'day-wrap-up', SPOUSE,
    t(F, 'playful', CA, '오늘 있었던 일 중에 웃겼던 거 하나만 말해 줘요.', '오늘 있었던 일 중에 웃겼던 거 하나만 말해 줘.'),
    t(S, 'thinking', CA, '음, 생각해 볼게요. 있었던 것 같아요.', '음, 생각해 볼게. 있었던 것 같아.')),
  b('spouse-61', 'dinner', SPOUSE,
    t(F, 'calm', CA, '오늘 저녁은 같이 천천히 먹어요.', '오늘 저녁은 같이 천천히 먹자.'),
    t(S, 'happy', CA, '좋아요. 급할 것 하나도 없으니까요.', '좋아. 급할 것 하나도 없으니까.')),
  b('spouse-62', 'pre-bedtime', SPOUSE,
    t(F, 'calm', CA, '오늘도 이렇게 하루를 같이 마무리하네요.', '오늘도 이렇게 하루를 같이 마무리하네.'),
    t(S, 'warm', CA, '이 시간이 매일 있다는 게 감사해요.', '이 시간이 매일 있다는 게 감사해.')),
  b('spouse-63', 'bedtime', SPOUSE,
    t(F, 'sleepy', AF, '먼저 잘게요. 옆에서 잘 자요.', '먼저 잘게. 옆에서 잘 자.'),
    t(S, 'warm', AF, '네, 좋은 꿈 꾸고 내일 봐요.', '응, 좋은 꿈 꾸고 내일 보자.')),
  b('spouse-64', 'bedtime', SPOUSE,
    t(F, 'calm', CA, '오늘도 무사히 하루를 같이 보냈네요.', '오늘도 무사히 하루를 같이 보냈네.'),
    t(S, 'warm', CA, '내일도 이렇게 같이 보내요.', '내일도 이렇게 같이 보내자.')),
  b('spouse-65', 'favor', SPOUSE,
    t(F, 'asking', CA, '부탁 하나 해도 돼요? 별건 아니에요.', '부탁 하나 해도 돼? 별건 아니야.'),
    t(S, 'willing', CA, '좋아요, 편하게 말해요.', '좋아, 편하게 말해.'),
    t(F, 'warm', CA, '그냥 오늘은 일찍 같이 쉬어요.', '그냥 오늘은 일찍 같이 쉬자.')),
  b('spouse-66', 'apology', SPOUSE,
    t(F, 'apologetic', AF, '아까 제가 무심하게 말한 것 같아요. 미안해요.', '아까 내가 무심하게 말한 것 같아. 미안해.'),
    t(S, 'calm', CA, '괜찮아요, 그럴 수도 있죠.', '괜찮아, 그럴 수도 있지.'),
    t(F, 'warm', AF, '그렇게 넘어가 줘서 고마워요.', '그렇게 넘어가 줘서 고마워.')),
  b('spouse-67', 'afternoon-chat', SPOUSE,
    t(F, 'gentle', AF, '오후엔 잠깐이라도 눈 좀 붙여요.', '오후엔 잠깐이라도 눈 좀 붙여.'),
    t(S, 'warm', CA, '그럴게요. 신경 써 줘서 고마워요.', '그럴게. 신경 써 줘서 고마워.')),
  b('spouse-68', 'snack', SPOUSE,
    t(F, 'happy', CA, '이거 같이 나눠 먹을까요?', '이거 같이 나눠 먹을까?'),
    t(S, 'happy', CA, '좋아요, 이런 소소한 게 좋아요.', '좋아, 이런 소소한 게 좋아.')),
  b('spouse-69', 'casual-chat', SPOUSE,
    t(F, 'calm', CA, '가만히 있어도 옆에 있는 게 느껴져서 좋아요.', '가만히 있어도 옆에 있는 게 느껴져서 좋아.'),
    t(S, 'warm', CA, '그 말, 저도 항상 느껴요.', '그 말, 나도 항상 느껴.')),
  b('spouse-70', 'encounter', SPOUSE,
    t(F, 'happy', AF, '이 시간에 여기서 볼 줄은 몰랐는데 반갑네요.', '이 시간에 여기서 볼 줄은 몰랐는데 반갑네.'),
    t(S, 'happy', CA, '저도요. 우연히 마주쳐도 좋네요.', '나도. 우연히 마주쳐도 좋네.')),
]

/** 연인·부부 공용 (20) */
export const SHARED_AFFECTION_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  b('affection-01', 'encounter', BOTH,
    t(F, 'happy', EN, '마침 잘 만났어요. 반가워요.', '마침 잘 만났다. 반가워.'),
    t(S, 'warm', AF, '저도요. 얼굴 보니까 좋아요.', '나도. 얼굴 보니까 좋아.')),
  b('affection-02', 'encounter', BOTH,
    t(F, 'happy', EN, '눈이 마주치니까 웃음이 나요.', '눈이 마주치니까 웃음이 나.'),
    t(S, 'happy', AF, '저도 똑같아요. 이유 없이 기분이 좋아져요.', '나도 똑같아. 이유 없이 기분이 좋아져.')),
  b('affection-03', 'morning-greeting', BOTH,
    t(F, 'warm', AF, '좋은 아침이에요. 오늘도 함께라서 좋아요.', '좋은 아침. 오늘도 함께라서 좋아.'),
    t(S, 'warm', AF, '저도요. 좋은 하루 시작해요.', '나도. 좋은 하루 시작하자.')),
  b('affection-04', 'lunch', BOTH,
    t(F, 'worried', AF, '밥은 거르지 말아요. 신경 쓰이니까요.', '밥은 거르지 마. 신경 쓰이니까.'),
    t(S, 'warm', AF, '네, 그 마음 알아서 잘 챙겨 먹을게요.', '응, 그 마음 알아서 잘 챙겨 먹을게.')),
  b('affection-05', 'compliment', BOTH,
    t(F, 'warm', AF, '오늘 모습이 참 마음에 들어요.', '오늘 모습이 참 마음에 들어.'),
    t(S, 'happy', SH, '그런 말 들으면 하루가 즐거워져요.', '그런 말 들으면 하루가 즐거워져.')),
  b('affection-06', 'teasing', BOTH,
    t(F, 'playful', PL, '가끔 너무 귀여운 건 반칙 아니에요?', '가끔 너무 귀여운 건 반칙 아니야?'),
    t(S, 'playful', PL, '귀여운 건 제 잘못이 아니에요.', '귀여운 건 내 잘못이 아니야.'),
    t(F, 'playful', PL, '그럼 인정할게요. 반칙 맞아요.', '그럼 인정할게. 반칙 맞아.')),
  b('affection-07', 'worried', BOTH,
    t(F, 'worried', AF, '무리하지 말아요. 걱정되니까요.', '무리하지 마. 걱정되니까.'),
    t(S, 'warm', AF, '네, 적당히 할게요. 걱정해 줘서 고마워요.', '응, 적당히 할게. 걱정해 줘서 고마워.')),
  b('affection-08', 'comfort', BOTH,
    t(F, 'gentle', AF, '언제든 기대도 돼요.', '언제든 기대도 돼.'),
    t(S, 'warm', CA, '알아요. 그래서 마음이 놓여요.', '알아. 그래서 마음이 놓여.')),
  b('affection-09', 'afternoon-chat', BOTH,
    t(F, 'warm', AF, '잠깐 같이 있을래요? 오후가 길어서요.', '잠깐 같이 있을래? 오후가 길어서.'),
    t(S, 'happy', EN, '좋아요. 그 제안 기다렸어요.', '좋아. 그 제안 기다렸어.')),
  b('affection-10', 'snack', BOTH,
    t(F, 'happy', AF, '이거 같이 먹으면 더 맛있을 것 같아서요.', '이거 같이 먹으면 더 맛있을 것 같아서.'),
    t(S, 'happy', AF, '그럼 기꺼이 나눠 먹어야죠.', '그럼 기꺼이 나눠 먹어야지.')),
  b('affection-11', 'resting-together', BOTH,
    t(F, 'calm', CA, '옆에 있으면 쉬는 게 더 편해요.', '옆에 있으면 쉬는 게 더 편해.'),
    t(S, 'calm', CA, '저도요. 같이 쉬는 게 제일 좋아요.', '나도. 같이 쉬는 게 제일 좋아.')),
  b('affection-12', 'calling-partner', BOTH,
    t(F, 'warm', AF, '잠깐 얼굴 보고 싶어서 불렀어요.', '잠깐 얼굴 보고 싶어서 불렀어.'),
    t(S, 'warm', AF, '잘 불렀어요. 저도 보고 싶었어요.', '잘 불렀어. 나도 보고 싶었어.')),
  b('affection-13', 'gratitude', BOTH,
    t(F, 'warm', AF, '함께여서 고마워요.', '함께여서 고마워.'),
    t(S, 'warm', AF, '저도요. 그 말이 참 따뜻해요.', '나도. 그 말이 참 따뜻해.')),
  b('affection-14', 'day-wrap-up', BOTH,
    t(F, 'warm', AF, '오늘 하루 잘 보냈어요? 편히 쉬어요.', '오늘 하루 잘 보냈어? 편히 쉬어.'),
    t(S, 'warm', CA, '네, 덕분에요. 이제 천천히 쉬어요.', '응, 덕분에. 이제 천천히 쉬자.')),
  b('affection-15', 'dinner', BOTH,
    t(F, 'happy', AF, '저녁 시간이네요. 같이 먹으면 좋겠어요.', '저녁 시간이네. 같이 먹으면 좋겠어.'),
    t(S, 'happy', EN, '네, 좋아요. 이야기도 나누면서요.', '응, 좋아. 이야기도 나누면서.')),
  b('affection-16', 'pre-bedtime', BOTH,
    t(F, 'calm', CA, '하루가 저물었네요. 마음이 편안해요.', '하루가 저물었네. 마음이 편안해.'),
    t(S, 'warm', CA, '함께 있어서 더 그런 것 같아요.', '함께 있어서 더 그런 것 같아.')),
  b('affection-17', 'bedtime', BOTH,
    t(F, 'sleepy', AF, '좋은 밤 보내요.', '좋은 밤 보내.'),
    t(S, 'warm', AF, '고마워요. 좋은 밤 보내요.', '고마워. 좋은 밤 보내.')),
  b('affection-18', 'casual-chat', BOTH,
    t(F, 'warm', AF, '같이 있으면 마음이 놓여요.', '같이 있으면 마음이 놓여.'),
    t(S, 'warm', CA, '저도요. 이런 느낌이 좋아요.', '나도. 이런 느낌이 좋아.')),
  b('affection-19', 'compliment', BOTH,
    t(F, 'warm', AF, '목소리를 듣고 있으면 편안해져요.', '목소리를 듣고 있으면 편안해져.'),
    t(S, 'happy', SH, '그런 말 들으니 계속 이야기하고 싶어져요.', '그런 말 들으니 계속 이야기하고 싶어져.')),
  b('affection-20', 'comfort', BOTH,
    t(F, 'gentle', AF, '오늘도 잘하고 있어요. 진심이에요.', '오늘도 잘하고 있어. 진심이야.'),
    t(S, 'warm', CA, '그렇게 말해 주는 사람이 있어서 힘이 나요.', '그렇게 말해 주는 사람이 있어서 힘이 나.')),
]

export const ROMANCE_DIALOGUE_BUNDLES: DefaultDialogueBundleDef[] = [
  ...LOVER_DIALOGUE_BUNDLES,
  ...SPOUSE_DIALOGUE_BUNDLES,
  ...SHARED_AFFECTION_DIALOGUE_BUNDLES,
]
